// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO rtu.attachments (
    entity_type, entity_id, s3_bucket, s3_key, original_name, mime_type,
    file_size, caption, created_by
)
VALUES (
    $1::varchar,
    $2::uuid,
    $3::varchar,
    $4::varchar,
    $5::varchar,
    $6::varchar,
    $7::bigint,
    $8::text,
    $9::uuid
)
RETURNING id, entity_type, entity_id, s3_bucket, s3_key, original_name, mime_type, file_size, caption, created_by, created_at, updated_at, updated_by
`

type CreateAttachmentParams struct {
	EntityType   string    `db:"entity_type" json:"entity_type"`
	EntityID     uuid.UUID `db:"entity_id" json:"entity_id"`
	S3Bucket     string    `db:"s3_bucket" json:"s3_bucket"`
	S3Key        string    `db:"s3_key" json:"s3_key"`
	OriginalName *string   `db:"original_name" json:"original_name"`
	MimeType     string    `db:"mime_type" json:"mime_type"`
	FileSize     int64     `db:"file_size" json:"file_size"`
	Caption      *string   `db:"caption" json:"caption"`
	CreatedBy    uuid.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.EntityType,
		arg.EntityID,
		arg.S3Bucket,
		arg.S3Key,
		arg.OriginalName,
		arg.MimeType,
		arg.FileSize,
		arg.Caption,
		arg.CreatedBy,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.S3Bucket,
		&i.S3Key,
		&i.OriginalName,
		&i.MimeType,
		&i.FileSize,
		&i.Caption,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteAttachment = `-- name: DeleteAttachment :execrows
DELETE FROM rtu.attachments WHERE id = $1::uuid
`

func (q *Queries) DeleteAttachment(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAttachment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, entity_type, entity_id, s3_bucket, s3_key, original_name, mime_type, file_size, caption, created_by, created_at, updated_at, updated_by FROM rtu.attachments WHERE id = $1::uuid
`

func (q *Queries) GetAttachment(ctx context.Context, id uuid.UUID) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachment, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.S3Bucket,
		&i.S3Key,
		&i.OriginalName,
		&i.MimeType,
		&i.FileSize,
		&i.Caption,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listAttachmentsByEntity = `-- name: ListAttachmentsByEntity :many
SELECT id, entity_type, entity_id, s3_bucket, s3_key, original_name, mime_type, file_size, caption, created_by, created_at, updated_at, updated_by FROM rtu.attachments
WHERE entity_type = $1::varchar AND entity_id = $2::uuid
ORDER BY created_at
`

type ListAttachmentsByEntityParams struct {
	EntityType string    `db:"entity_type" json:"entity_type"`
	EntityID   uuid.UUID `db:"entity_id" json:"entity_id"`
}

func (q *Queries) ListAttachmentsByEntity(ctx context.Context, arg ListAttachmentsByEntityParams) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.S3Bucket,
			&i.S3Key,
			&i.OriginalName,
			&i.MimeType,
			&i.FileSize,
			&i.Caption,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAttachmentCaption = `-- name: UpdateAttachmentCaption :one
UPDATE rtu.attachments SET
    caption    = $1::text,
    updated_by = $2::uuid
WHERE id = $3::uuid
RETURNING id, entity_type, entity_id, s3_bucket, s3_key, original_name, mime_type, file_size, caption, created_by, created_at, updated_at, updated_by
`

type UpdateAttachmentCaptionParams struct {
	Caption   *string    `db:"caption" json:"caption"`
	UpdatedBy *uuid.UUID `db:"updated_by" json:"updated_by"`
	ID        uuid.UUID  `db:"id" json:"id"`
}

func (q *Queries) UpdateAttachmentCaption(ctx context.Context, arg UpdateAttachmentCaptionParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, updateAttachmentCaption, arg.Caption, arg.UpdatedBy, arg.ID)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.S3Bucket,
		&i.S3Key,
		&i.OriginalName,
		&i.MimeType,
		&i.FileSize,
		&i.Caption,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
