// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO rtu.audit_logs (
    user_id, action, method, path, resource, resource_id,
    status_code, ip_address, user_agent, request_id
)
VALUES (
    $1::uuid,
    $2::varchar,
    $3::varchar,
    $4::text,
    $5::varchar,
    $6::uuid,
    $7::integer,
    $8::varchar,
    $9::text,
    $10::varchar
)
RETURNING id, user_id, action, method, path, resource, resource_id, status_code, ip_address, user_agent, request_id, created_at
`

type CreateAuditLogParams struct {
	UserID     *uuid.UUID `db:"user_id" json:"user_id"`
	Action     string     `db:"action" json:"action"`
	Method     string     `db:"method" json:"method"`
	Path       string     `db:"path" json:"path"`
	Resource   *string    `db:"resource" json:"resource"`
	ResourceID *uuid.UUID `db:"resource_id" json:"resource_id"`
	StatusCode *int32     `db:"status_code" json:"status_code"`
	IpAddress  *string    `db:"ip_address" json:"ip_address"`
	UserAgent  *string    `db:"user_agent" json:"user_agent"`
	RequestID  *string    `db:"request_id" json:"request_id"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.UserID,
		arg.Action,
		arg.Method,
		arg.Path,
		arg.Resource,
		arg.ResourceID,
		arg.StatusCode,
		arg.IpAddress,
		arg.UserAgent,
		arg.RequestID,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.Method,
		&i.Path,
		&i.Resource,
		&i.ResourceID,
		&i.StatusCode,
		&i.IpAddress,
		&i.UserAgent,
		&i.RequestID,
		&i.CreatedAt,
	)
	return i, err
}
