// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calibrations.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const calibrationExists = `-- name: CalibrationExists :one
SELECT EXISTS (SELECT 1 FROM rtu.calibrations WHERE id = $1::uuid) AS found
`

func (q *Queries) CalibrationExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, calibrationExists, id)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const countCalibrationsByResult = `-- name: CountCalibrationsByResult :many
SELECT result, count(*)::bigint AS total
FROM rtu.calibrations
WHERE ($1::uuid IS NULL OR panel_device_id = $1::uuid)
  AND ($2::timestamptz IS NULL OR performed_at >= $2::timestamptz)
  AND ($3::timestamptz IS NULL OR performed_at <= $3::timestamptz)
GROUP BY result
`

type CountCalibrationsByResultParams struct {
	PanelDeviceID *uuid.UUID `db:"panel_device_id" json:"panel_device_id"`
	PerformedFrom *time.Time `db:"performed_from" json:"performed_from"`
	PerformedTo   *time.Time `db:"performed_to" json:"performed_to"`
}

type CountCalibrationsByResultRow struct {
	Result string `db:"result" json:"result"`
	Total  int64  `db:"total" json:"total"`
}

func (q *Queries) CountCalibrationsByResult(ctx context.Context, arg CountCalibrationsByResultParams) ([]CountCalibrationsByResultRow, error) {
	rows, err := q.db.Query(ctx, countCalibrationsByResult, arg.PanelDeviceID, arg.PerformedFrom, arg.PerformedTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountCalibrationsByResultRow{}
	for rows.Next() {
		var i CountCalibrationsByResultRow
		if err := rows.Scan(&i.Result, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCalibration = `-- name: CreateCalibration :one
INSERT INTO rtu.calibrations (
    panel_device_id, instrument_id, performed_by, performed_at, result, remark,
    work_order_id, pm_report_id, channel_type,
    eut_manufacturer, eut_model, eut_serial_no, eut_input_range,
    eut_accuracy_class, eut_power_supply, eut_output_range,
    result_type, result_other_text,
    created_by, updated_by
)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::varchar,
    $4::timestamptz,
    $5::varchar,
    $6::text,
    $7::uuid,
    $8::uuid,
    $9::varchar,
    $10::varchar,
    $11::varchar,
    $12::varchar,
    $13::varchar,
    $14::varchar,
    $15::varchar,
    $16::varchar,
    $17::varchar,
    $18::varchar,
    $19::uuid,
    $20::uuid
)
RETURNING id, panel_device_id, instrument_id, performed_by, performed_at, result, remark, created_at, updated_at, created_by, updated_by, work_order_id, pm_report_id, channel_type, eut_manufacturer, eut_model, eut_serial_no, eut_input_range, eut_accuracy_class, eut_power_supply, eut_output_range, result_type, result_other_text
`

type CreateCalibrationParams struct {
	PanelDeviceID    uuid.UUID  `db:"panel_device_id" json:"panel_device_id"`
	InstrumentID     uuid.UUID  `db:"instrument_id" json:"instrument_id"`
	PerformedBy      *string    `db:"performed_by" json:"performed_by"`
	PerformedAt      time.Time  `db:"performed_at" json:"performed_at"`
	Result           string     `db:"result" json:"result"`
	Remark           *string    `db:"remark" json:"remark"`
	WorkOrderID      *uuid.UUID `db:"work_order_id" json:"work_order_id"`
	PmReportID       *uuid.UUID `db:"pm_report_id" json:"pm_report_id"`
	ChannelType      *string    `db:"channel_type" json:"channel_type"`
	EutManufacturer  *string    `db:"eut_manufacturer" json:"eut_manufacturer"`
	EutModel         *string    `db:"eut_model" json:"eut_model"`
	EutSerialNo      *string    `db:"eut_serial_no" json:"eut_serial_no"`
	EutInputRange    *string    `db:"eut_input_range" json:"eut_input_range"`
	EutAccuracyClass *string    `db:"eut_accuracy_class" json:"eut_accuracy_class"`
	EutPowerSupply   *string    `db:"eut_power_supply" json:"eut_power_supply"`
	EutOutputRange   *string    `db:"eut_output_range" json:"eut_output_range"`
	ResultType       *string    `db:"result_type" json:"result_type"`
	ResultOtherText  *string    `db:"result_other_text" json:"result_other_text"`
	CreatedBy        *uuid.UUID `db:"created_by" json:"created_by"`
	UpdatedBy        *uuid.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) CreateCalibration(ctx context.Context, arg CreateCalibrationParams) (Calibration, error) {
	row := q.db.QueryRow(ctx, createCalibration,
		arg.PanelDeviceID,
		arg.InstrumentID,
		arg.PerformedBy,
		arg.PerformedAt,
		arg.Result,
		arg.Remark,
		arg.WorkOrderID,
		arg.PmReportID,
		arg.ChannelType,
		arg.EutManufacturer,
		arg.EutModel,
		arg.EutSerialNo,
		arg.EutInputRange,
		arg.EutAccuracyClass,
		arg.EutPowerSupply,
		arg.EutOutputRange,
		arg.ResultType,
		arg.ResultOtherText,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Calibration
	err := row.Scan(
		&i.ID,
		&i.PanelDeviceID,
		&i.InstrumentID,
		&i.PerformedBy,
		&i.PerformedAt,
		&i.Result,
		&i.Remark,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.WorkOrderID,
		&i.PmReportID,
		&i.ChannelType,
		&i.EutManufacturer,
		&i.EutModel,
		&i.EutSerialNo,
		&i.EutInputRange,
		&i.EutAccuracyClass,
		&i.EutPowerSupply,
		&i.EutOutputRange,
		&i.ResultType,
		&i.ResultOtherText,
	)
	return i, err
}

const deleteCalibration = `-- name: DeleteCalibration :execrows
DELETE FROM rtu.calibrations WHERE id = $1::uuid
`

func (q *Queries) DeleteCalibration(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCalibration, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCalibration = `-- name: GetCalibration :one
SELECT id, panel_device_id, instrument_id, performed_by, performed_at, result, remark, created_at, updated_at, created_by, updated_by, work_order_id, pm_report_id, channel_type, eut_manufacturer, eut_model, eut_serial_no, eut_input_range, eut_accuracy_class, eut_power_supply, eut_output_range, result_type, result_other_text FROM rtu.calibrations WHERE id = $1::uuid
`

func (q *Queries) GetCalibration(ctx context.Context, id uuid.UUID) (Calibration, error) {
	row := q.db.QueryRow(ctx, getCalibration, id)
	var i Calibration
	err := row.Scan(
		&i.ID,
		&i.PanelDeviceID,
		&i.InstrumentID,
		&i.PerformedBy,
		&i.PerformedAt,
		&i.Result,
		&i.Remark,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.WorkOrderID,
		&i.PmReportID,
		&i.ChannelType,
		&i.EutManufacturer,
		&i.EutModel,
		&i.EutSerialNo,
		&i.EutInputRange,
		&i.EutAccuracyClass,
		&i.EutPowerSupply,
		&i.EutOutputRange,
		&i.ResultType,
		&i.ResultOtherText,
	)
	return i, err
}

const getLatestCalibrationForDevice = `-- name: GetLatestCalibrationForDevice :one
SELECT id, panel_device_id, instrument_id, performed_by, performed_at, result, remark, created_at, updated_at, created_by, updated_by, work_order_id, pm_report_id, channel_type, eut_manufacturer, eut_model, eut_serial_no, eut_input_range, eut_accuracy_class, eut_power_supply, eut_output_range, result_type, result_other_text FROM rtu.calibrations
WHERE panel_device_id = $1::uuid
ORDER BY performed_at DESC
LIMIT 1
`

func (q *Queries) GetLatestCalibrationForDevice(ctx context.Context, panelDeviceID uuid.UUID) (Calibration, error) {
	row := q.db.QueryRow(ctx, getLatestCalibrationForDevice, panelDeviceID)
	var i Calibration
	err := row.Scan(
		&i.ID,
		&i.PanelDeviceID,
		&i.InstrumentID,
		&i.PerformedBy,
		&i.PerformedAt,
		&i.Result,
		&i.Remark,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.WorkOrderID,
		&i.PmReportID,
		&i.ChannelType,
		&i.EutManufacturer,
		&i.EutModel,
		&i.EutSerialNo,
		&i.EutInputRange,
		&i.EutAccuracyClass,
		&i.EutPowerSupply,
		&i.EutOutputRange,
		&i.ResultType,
		&i.ResultOtherText,
	)
	return i, err
}

const listCalibrationsByPmReport = `-- name: ListCalibrationsByPmReport :many
SELECT id, panel_device_id, instrument_id, performed_by, performed_at, result, remark, created_at, updated_at, created_by, updated_by, work_order_id, pm_report_id, channel_type, eut_manufacturer, eut_model, eut_serial_no, eut_input_range, eut_accuracy_class, eut_power_supply, eut_output_range, result_type, result_other_text FROM rtu.calibrations WHERE pm_report_id = $1::uuid ORDER BY performed_at
`

func (q *Queries) ListCalibrationsByPmReport(ctx context.Context, pmReportID uuid.UUID) ([]Calibration, error) {
	rows, err := q.db.Query(ctx, listCalibrationsByPmReport, pmReportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Calibration{}
	for rows.Next() {
		var i Calibration
		if err := rows.Scan(
			&i.ID,
			&i.PanelDeviceID,
			&i.InstrumentID,
			&i.PerformedBy,
			&i.PerformedAt,
			&i.Result,
			&i.Remark,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.WorkOrderID,
			&i.PmReportID,
			&i.ChannelType,
			&i.EutManufacturer,
			&i.EutModel,
			&i.EutSerialNo,
			&i.EutInputRange,
			&i.EutAccuracyClass,
			&i.EutPowerSupply,
			&i.EutOutputRange,
			&i.ResultType,
			&i.ResultOtherText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCalibrationsForPmReport = `-- name: ListCalibrationsForPmReport :many
SELECT id, panel_device_id, instrument_id, performed_by, performed_at, result, remark, created_at, updated_at, created_by, updated_by, work_order_id, pm_report_id, channel_type, eut_manufacturer, eut_model, eut_serial_no, eut_input_range, eut_accuracy_class, eut_power_supply, eut_output_range, result_type, result_other_text FROM rtu.calibrations
WHERE pm_report_id = $1::uuid
   OR (work_order_id = $2::uuid AND pm_report_id IS NULL)
ORDER BY performed_at
`

type ListCalibrationsForPmReportParams struct {
	PmReportID  uuid.UUID `db:"pm_report_id" json:"pm_report_id"`
	WorkOrderID uuid.UUID `db:"work_order_id" json:"work_order_id"`
}

// Includes calibrations linked directly to the report and those linked only
// to the PM work order (pm_report_id NULL) for submit/detail consistency.
func (q *Queries) ListCalibrationsForPmReport(ctx context.Context, arg ListCalibrationsForPmReportParams) ([]Calibration, error) {
	rows, err := q.db.Query(ctx, listCalibrationsForPmReport, arg.PmReportID, arg.WorkOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Calibration{}
	for rows.Next() {
		var i Calibration
		if err := rows.Scan(
			&i.ID,
			&i.PanelDeviceID,
			&i.InstrumentID,
			&i.PerformedBy,
			&i.PerformedAt,
			&i.Result,
			&i.Remark,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.WorkOrderID,
			&i.PmReportID,
			&i.ChannelType,
			&i.EutManufacturer,
			&i.EutModel,
			&i.EutSerialNo,
			&i.EutInputRange,
			&i.EutAccuracyClass,
			&i.EutPowerSupply,
			&i.EutOutputRange,
			&i.ResultType,
			&i.ResultOtherText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCalibration = `-- name: UpdateCalibration :one
UPDATE rtu.calibrations SET
    panel_device_id    = CASE WHEN $1::boolean THEN $2::uuid ELSE panel_device_id END,
    instrument_id       = CASE WHEN $3::boolean THEN $4::uuid ELSE instrument_id END,
    performed_by        = CASE WHEN $5::boolean THEN $6::varchar ELSE performed_by END,
    performed_at        = CASE WHEN $7::boolean THEN $8::timestamptz ELSE performed_at END,
    result              = CASE WHEN $9::boolean THEN $10::varchar ELSE result END,
    remark              = CASE WHEN $11::boolean THEN $12::text ELSE remark END,
    work_order_id       = CASE WHEN $13::boolean THEN $14::uuid ELSE work_order_id END,
    pm_report_id        = CASE WHEN $15::boolean THEN $16::uuid ELSE pm_report_id END,
    channel_type        = CASE WHEN $17::boolean THEN $18::varchar ELSE channel_type END,
    eut_manufacturer    = CASE WHEN $19::boolean THEN $20::varchar ELSE eut_manufacturer END,
    eut_model           = CASE WHEN $21::boolean THEN $22::varchar ELSE eut_model END,
    eut_serial_no       = CASE WHEN $23::boolean THEN $24::varchar ELSE eut_serial_no END,
    eut_input_range     = CASE WHEN $25::boolean THEN $26::varchar ELSE eut_input_range END,
    eut_accuracy_class  = CASE WHEN $27::boolean THEN $28::varchar ELSE eut_accuracy_class END,
    eut_power_supply    = CASE WHEN $29::boolean THEN $30::varchar ELSE eut_power_supply END,
    eut_output_range    = CASE WHEN $31::boolean THEN $32::varchar ELSE eut_output_range END,
    result_type         = CASE WHEN $33::boolean THEN $34::varchar ELSE result_type END,
    result_other_text   = CASE WHEN $35::boolean THEN $36::varchar ELSE result_other_text END,
    updated_by          = $37::uuid
WHERE id = $38::uuid
RETURNING id, panel_device_id, instrument_id, performed_by, performed_at, result, remark, created_at, updated_at, created_by, updated_by, work_order_id, pm_report_id, channel_type, eut_manufacturer, eut_model, eut_serial_no, eut_input_range, eut_accuracy_class, eut_power_supply, eut_output_range, result_type, result_other_text
`

type UpdateCalibrationParams struct {
	PanelDeviceIDDoUpdate    bool       `db:"panel_device_id_do_update" json:"panel_device_id_do_update"`
	PanelDeviceID            uuid.UUID  `db:"panel_device_id" json:"panel_device_id"`
	InstrumentIDDoUpdate     bool       `db:"instrument_id_do_update" json:"instrument_id_do_update"`
	InstrumentID             uuid.UUID  `db:"instrument_id" json:"instrument_id"`
	PerformedByDoUpdate      bool       `db:"performed_by_do_update" json:"performed_by_do_update"`
	PerformedBy              *string    `db:"performed_by" json:"performed_by"`
	PerformedAtDoUpdate      bool       `db:"performed_at_do_update" json:"performed_at_do_update"`
	PerformedAt              time.Time  `db:"performed_at" json:"performed_at"`
	ResultDoUpdate           bool       `db:"result_do_update" json:"result_do_update"`
	Result                   string     `db:"result" json:"result"`
	RemarkDoUpdate           bool       `db:"remark_do_update" json:"remark_do_update"`
	Remark                   *string    `db:"remark" json:"remark"`
	WorkOrderIDDoUpdate      bool       `db:"work_order_id_do_update" json:"work_order_id_do_update"`
	WorkOrderID              *uuid.UUID `db:"work_order_id" json:"work_order_id"`
	PmReportIDDoUpdate       bool       `db:"pm_report_id_do_update" json:"pm_report_id_do_update"`
	PmReportID               *uuid.UUID `db:"pm_report_id" json:"pm_report_id"`
	ChannelTypeDoUpdate      bool       `db:"channel_type_do_update" json:"channel_type_do_update"`
	ChannelType              *string    `db:"channel_type" json:"channel_type"`
	EutManufacturerDoUpdate  bool       `db:"eut_manufacturer_do_update" json:"eut_manufacturer_do_update"`
	EutManufacturer          *string    `db:"eut_manufacturer" json:"eut_manufacturer"`
	EutModelDoUpdate         bool       `db:"eut_model_do_update" json:"eut_model_do_update"`
	EutModel                 *string    `db:"eut_model" json:"eut_model"`
	EutSerialNoDoUpdate      bool       `db:"eut_serial_no_do_update" json:"eut_serial_no_do_update"`
	EutSerialNo              *string    `db:"eut_serial_no" json:"eut_serial_no"`
	EutInputRangeDoUpdate    bool       `db:"eut_input_range_do_update" json:"eut_input_range_do_update"`
	EutInputRange            *string    `db:"eut_input_range" json:"eut_input_range"`
	EutAccuracyClassDoUpdate bool       `db:"eut_accuracy_class_do_update" json:"eut_accuracy_class_do_update"`
	EutAccuracyClass         *string    `db:"eut_accuracy_class" json:"eut_accuracy_class"`
	EutPowerSupplyDoUpdate   bool       `db:"eut_power_supply_do_update" json:"eut_power_supply_do_update"`
	EutPowerSupply           *string    `db:"eut_power_supply" json:"eut_power_supply"`
	EutOutputRangeDoUpdate   bool       `db:"eut_output_range_do_update" json:"eut_output_range_do_update"`
	EutOutputRange           *string    `db:"eut_output_range" json:"eut_output_range"`
	ResultTypeDoUpdate       bool       `db:"result_type_do_update" json:"result_type_do_update"`
	ResultType               *string    `db:"result_type" json:"result_type"`
	ResultOtherTextDoUpdate  bool       `db:"result_other_text_do_update" json:"result_other_text_do_update"`
	ResultOtherText          *string    `db:"result_other_text" json:"result_other_text"`
	UpdatedBy                *uuid.UUID `db:"updated_by" json:"updated_by"`
	ID                       uuid.UUID  `db:"id" json:"id"`
}

func (q *Queries) UpdateCalibration(ctx context.Context, arg UpdateCalibrationParams) (Calibration, error) {
	row := q.db.QueryRow(ctx, updateCalibration,
		arg.PanelDeviceIDDoUpdate,
		arg.PanelDeviceID,
		arg.InstrumentIDDoUpdate,
		arg.InstrumentID,
		arg.PerformedByDoUpdate,
		arg.PerformedBy,
		arg.PerformedAtDoUpdate,
		arg.PerformedAt,
		arg.ResultDoUpdate,
		arg.Result,
		arg.RemarkDoUpdate,
		arg.Remark,
		arg.WorkOrderIDDoUpdate,
		arg.WorkOrderID,
		arg.PmReportIDDoUpdate,
		arg.PmReportID,
		arg.ChannelTypeDoUpdate,
		arg.ChannelType,
		arg.EutManufacturerDoUpdate,
		arg.EutManufacturer,
		arg.EutModelDoUpdate,
		arg.EutModel,
		arg.EutSerialNoDoUpdate,
		arg.EutSerialNo,
		arg.EutInputRangeDoUpdate,
		arg.EutInputRange,
		arg.EutAccuracyClassDoUpdate,
		arg.EutAccuracyClass,
		arg.EutPowerSupplyDoUpdate,
		arg.EutPowerSupply,
		arg.EutOutputRangeDoUpdate,
		arg.EutOutputRange,
		arg.ResultTypeDoUpdate,
		arg.ResultType,
		arg.ResultOtherTextDoUpdate,
		arg.ResultOtherText,
		arg.UpdatedBy,
		arg.ID,
	)
	var i Calibration
	err := row.Scan(
		&i.ID,
		&i.PanelDeviceID,
		&i.InstrumentID,
		&i.PerformedBy,
		&i.PerformedAt,
		&i.Result,
		&i.Remark,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.WorkOrderID,
		&i.PmReportID,
		&i.ChannelType,
		&i.EutManufacturer,
		&i.EutModel,
		&i.EutSerialNo,
		&i.EutInputRange,
		&i.EutAccuracyClass,
		&i.EutPowerSupply,
		&i.EutOutputRange,
		&i.ResultType,
		&i.ResultOtherText,
	)
	return i, err
}
