// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calibration_instruments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/rtu-api/internal/httpx"
)

const calibrationInstrumentExists = `-- name: CalibrationInstrumentExists :one
SELECT EXISTS (SELECT 1 FROM rtu.calibration_instruments WHERE id = $1::uuid) AS found
`

func (q *Queries) CalibrationInstrumentExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, calibrationInstrumentExists, id)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const createCalibrationInstrument = `-- name: CreateCalibrationInstrument :one
INSERT INTO rtu.calibration_instruments (
    name, equipment_type, manufacturer, brand, model, serial_number,
    calibration_date, expire_date, active,
    created_by, updated_by
)
VALUES (
    $1::varchar,
    $2::varchar,
    $3::varchar,
    $4::varchar,
    $5::varchar,
    $6::varchar,
    $7::date,
    $8::date,
    COALESCE($9::boolean, true),
    $10::uuid,
    $11::uuid
)
RETURNING id, name, manufacturer, model, serial_number, calibration_date, expire_date, active, created_at, updated_at, created_by, updated_by, equipment_type, brand
`

type CreateCalibrationInstrumentParams struct {
	Name            string      `db:"name" json:"name"`
	EquipmentType   *string     `db:"equipment_type" json:"equipment_type"`
	Manufacturer    *string     `db:"manufacturer" json:"manufacturer"`
	Brand           *string     `db:"brand" json:"brand"`
	Model           *string     `db:"model" json:"model"`
	SerialNumber    *string     `db:"serial_number" json:"serial_number"`
	CalibrationDate *httpx.Date `db:"calibration_date" json:"calibration_date"`
	ExpireDate      *httpx.Date `db:"expire_date" json:"expire_date"`
	Active          *bool       `db:"active" json:"active"`
	CreatedBy       *uuid.UUID  `db:"created_by" json:"created_by"`
	UpdatedBy       *uuid.UUID  `db:"updated_by" json:"updated_by"`
}

func (q *Queries) CreateCalibrationInstrument(ctx context.Context, arg CreateCalibrationInstrumentParams) (CalibrationInstrument, error) {
	row := q.db.QueryRow(ctx, createCalibrationInstrument,
		arg.Name,
		arg.EquipmentType,
		arg.Manufacturer,
		arg.Brand,
		arg.Model,
		arg.SerialNumber,
		arg.CalibrationDate,
		arg.ExpireDate,
		arg.Active,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i CalibrationInstrument
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Manufacturer,
		&i.Model,
		&i.SerialNumber,
		&i.CalibrationDate,
		&i.ExpireDate,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.EquipmentType,
		&i.Brand,
	)
	return i, err
}

const deleteCalibrationInstrument = `-- name: DeleteCalibrationInstrument :execrows
DELETE FROM rtu.calibration_instruments WHERE id = $1::uuid
`

func (q *Queries) DeleteCalibrationInstrument(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCalibrationInstrument, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCalibrationInstrument = `-- name: GetCalibrationInstrument :one
SELECT id, name, manufacturer, model, serial_number, calibration_date, expire_date, active, created_at, updated_at, created_by, updated_by, equipment_type, brand FROM rtu.calibration_instruments WHERE id = $1::uuid
`

func (q *Queries) GetCalibrationInstrument(ctx context.Context, id uuid.UUID) (CalibrationInstrument, error) {
	row := q.db.QueryRow(ctx, getCalibrationInstrument, id)
	var i CalibrationInstrument
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Manufacturer,
		&i.Model,
		&i.SerialNumber,
		&i.CalibrationDate,
		&i.ExpireDate,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.EquipmentType,
		&i.Brand,
	)
	return i, err
}

const getCalibrationInstrumentUsability = `-- name: GetCalibrationInstrumentUsability :one
SELECT active, expire_date FROM rtu.calibration_instruments WHERE id = $1::uuid
`

type GetCalibrationInstrumentUsabilityRow struct {
	Active     bool        `db:"active" json:"active"`
	ExpireDate *httpx.Date `db:"expire_date" json:"expire_date"`
}

func (q *Queries) GetCalibrationInstrumentUsability(ctx context.Context, id uuid.UUID) (GetCalibrationInstrumentUsabilityRow, error) {
	row := q.db.QueryRow(ctx, getCalibrationInstrumentUsability, id)
	var i GetCalibrationInstrumentUsabilityRow
	err := row.Scan(&i.Active, &i.ExpireDate)
	return i, err
}

const setCalibrationInstrumentActive = `-- name: SetCalibrationInstrumentActive :one
UPDATE rtu.calibration_instruments SET
    active     = $1::boolean,
    updated_by = $2::uuid
WHERE id = $3::uuid
RETURNING id, name, manufacturer, model, serial_number, calibration_date, expire_date, active, created_at, updated_at, created_by, updated_by, equipment_type, brand
`

type SetCalibrationInstrumentActiveParams struct {
	Active    bool       `db:"active" json:"active"`
	UpdatedBy *uuid.UUID `db:"updated_by" json:"updated_by"`
	ID        uuid.UUID  `db:"id" json:"id"`
}

func (q *Queries) SetCalibrationInstrumentActive(ctx context.Context, arg SetCalibrationInstrumentActiveParams) (CalibrationInstrument, error) {
	row := q.db.QueryRow(ctx, setCalibrationInstrumentActive, arg.Active, arg.UpdatedBy, arg.ID)
	var i CalibrationInstrument
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Manufacturer,
		&i.Model,
		&i.SerialNumber,
		&i.CalibrationDate,
		&i.ExpireDate,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.EquipmentType,
		&i.Brand,
	)
	return i, err
}

const updateCalibrationInstrument = `-- name: UpdateCalibrationInstrument :one
UPDATE rtu.calibration_instruments SET
    name             = CASE WHEN $1::boolean THEN $2::varchar ELSE name END,
    equipment_type   = CASE WHEN $3::boolean THEN $4::varchar ELSE equipment_type END,
    manufacturer     = CASE WHEN $5::boolean THEN $6::varchar ELSE manufacturer END,
    brand            = CASE WHEN $7::boolean THEN $8::varchar ELSE brand END,
    model            = CASE WHEN $9::boolean THEN $10::varchar ELSE model END,
    serial_number    = CASE WHEN $11::boolean THEN $12::varchar ELSE serial_number END,
    calibration_date = CASE WHEN $13::boolean THEN $14::date ELSE calibration_date END,
    expire_date      = CASE WHEN $15::boolean THEN $16::date ELSE expire_date END,
    active           = CASE WHEN $17::boolean THEN $18::boolean ELSE active END,
    updated_by       = $19::uuid
WHERE id = $20::uuid
RETURNING id, name, manufacturer, model, serial_number, calibration_date, expire_date, active, created_at, updated_at, created_by, updated_by, equipment_type, brand
`

type UpdateCalibrationInstrumentParams struct {
	NameDoUpdate            bool        `db:"name_do_update" json:"name_do_update"`
	Name                    string      `db:"name" json:"name"`
	EquipmentTypeDoUpdate   bool        `db:"equipment_type_do_update" json:"equipment_type_do_update"`
	EquipmentType           *string     `db:"equipment_type" json:"equipment_type"`
	ManufacturerDoUpdate    bool        `db:"manufacturer_do_update" json:"manufacturer_do_update"`
	Manufacturer            *string     `db:"manufacturer" json:"manufacturer"`
	BrandDoUpdate           bool        `db:"brand_do_update" json:"brand_do_update"`
	Brand                   *string     `db:"brand" json:"brand"`
	ModelDoUpdate           bool        `db:"model_do_update" json:"model_do_update"`
	Model                   *string     `db:"model" json:"model"`
	SerialNumberDoUpdate    bool        `db:"serial_number_do_update" json:"serial_number_do_update"`
	SerialNumber            *string     `db:"serial_number" json:"serial_number"`
	CalibrationDateDoUpdate bool        `db:"calibration_date_do_update" json:"calibration_date_do_update"`
	CalibrationDate         *httpx.Date `db:"calibration_date" json:"calibration_date"`
	ExpireDateDoUpdate      bool        `db:"expire_date_do_update" json:"expire_date_do_update"`
	ExpireDate              *httpx.Date `db:"expire_date" json:"expire_date"`
	ActiveDoUpdate          bool        `db:"active_do_update" json:"active_do_update"`
	Active                  bool        `db:"active" json:"active"`
	UpdatedBy               *uuid.UUID  `db:"updated_by" json:"updated_by"`
	ID                      uuid.UUID   `db:"id" json:"id"`
}

func (q *Queries) UpdateCalibrationInstrument(ctx context.Context, arg UpdateCalibrationInstrumentParams) (CalibrationInstrument, error) {
	row := q.db.QueryRow(ctx, updateCalibrationInstrument,
		arg.NameDoUpdate,
		arg.Name,
		arg.EquipmentTypeDoUpdate,
		arg.EquipmentType,
		arg.ManufacturerDoUpdate,
		arg.Manufacturer,
		arg.BrandDoUpdate,
		arg.Brand,
		arg.ModelDoUpdate,
		arg.Model,
		arg.SerialNumberDoUpdate,
		arg.SerialNumber,
		arg.CalibrationDateDoUpdate,
		arg.CalibrationDate,
		arg.ExpireDateDoUpdate,
		arg.ExpireDate,
		arg.ActiveDoUpdate,
		arg.Active,
		arg.UpdatedBy,
		arg.ID,
	)
	var i CalibrationInstrument
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Manufacturer,
		&i.Model,
		&i.SerialNumber,
		&i.CalibrationDate,
		&i.ExpireDate,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.EquipmentType,
		&i.Brand,
	)
	return i, err
}
