// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calibration_readings.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type BulkCreateCalibrationReadingsParams struct {
	CalibrationID uuid.UUID        `db:"calibration_id" json:"calibration_id"`
	Sequence      int16            `db:"sequence" json:"sequence"`
	ItemLabel     *string          `db:"item_label" json:"item_label"`
	ParameterKey  string           `db:"parameter_key" json:"parameter_key"`
	Value         *decimal.Decimal `db:"value" json:"value"`
	Unit          *string          `db:"unit" json:"unit"`
	CreatedBy     *uuid.UUID       `db:"created_by" json:"created_by"`
}

const createCalibrationReading = `-- name: CreateCalibrationReading :one
INSERT INTO rtu.calibration_readings (
    calibration_id, sequence, item_label, parameter_key, value, unit,
    created_by, updated_by
)
VALUES (
    $1::uuid,
    $2::smallint,
    $3::varchar,
    $4::varchar,
    $5::numeric,
    $6::varchar,
    $7::uuid,
    $8::uuid
)
RETURNING id, calibration_id, sequence, item_label, parameter_key, value, unit, created_at, created_by, updated_by, updated_at
`

type CreateCalibrationReadingParams struct {
	CalibrationID uuid.UUID        `db:"calibration_id" json:"calibration_id"`
	Sequence      int16            `db:"sequence" json:"sequence"`
	ItemLabel     *string          `db:"item_label" json:"item_label"`
	ParameterKey  string           `db:"parameter_key" json:"parameter_key"`
	Value         *decimal.Decimal `db:"value" json:"value"`
	Unit          *string          `db:"unit" json:"unit"`
	CreatedBy     *uuid.UUID       `db:"created_by" json:"created_by"`
	UpdatedBy     *uuid.UUID       `db:"updated_by" json:"updated_by"`
}

func (q *Queries) CreateCalibrationReading(ctx context.Context, arg CreateCalibrationReadingParams) (CalibrationReading, error) {
	row := q.db.QueryRow(ctx, createCalibrationReading,
		arg.CalibrationID,
		arg.Sequence,
		arg.ItemLabel,
		arg.ParameterKey,
		arg.Value,
		arg.Unit,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i CalibrationReading
	err := row.Scan(
		&i.ID,
		&i.CalibrationID,
		&i.Sequence,
		&i.ItemLabel,
		&i.ParameterKey,
		&i.Value,
		&i.Unit,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCalibrationReading = `-- name: DeleteCalibrationReading :execrows
DELETE FROM rtu.calibration_readings WHERE id = $1::uuid
`

func (q *Queries) DeleteCalibrationReading(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCalibrationReading, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCalibrationReadingsByCalibration = `-- name: DeleteCalibrationReadingsByCalibration :execrows
DELETE FROM rtu.calibration_readings WHERE calibration_id = $1::uuid
`

func (q *Queries) DeleteCalibrationReadingsByCalibration(ctx context.Context, calibrationID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCalibrationReadingsByCalibration, calibrationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCalibrationReading = `-- name: GetCalibrationReading :one
SELECT id, calibration_id, sequence, item_label, parameter_key, value, unit, created_at, created_by, updated_by, updated_at FROM rtu.calibration_readings WHERE id = $1::uuid
`

func (q *Queries) GetCalibrationReading(ctx context.Context, id uuid.UUID) (CalibrationReading, error) {
	row := q.db.QueryRow(ctx, getCalibrationReading, id)
	var i CalibrationReading
	err := row.Scan(
		&i.ID,
		&i.CalibrationID,
		&i.Sequence,
		&i.ItemLabel,
		&i.ParameterKey,
		&i.Value,
		&i.Unit,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getCalibrationReadingForCalibration = `-- name: GetCalibrationReadingForCalibration :one
SELECT id, calibration_id, sequence, item_label, parameter_key, value, unit, created_at, created_by, updated_by, updated_at FROM rtu.calibration_readings
WHERE id = $1::uuid AND calibration_id = $2::uuid
`

type GetCalibrationReadingForCalibrationParams struct {
	ID            uuid.UUID `db:"id" json:"id"`
	CalibrationID uuid.UUID `db:"calibration_id" json:"calibration_id"`
}

func (q *Queries) GetCalibrationReadingForCalibration(ctx context.Context, arg GetCalibrationReadingForCalibrationParams) (CalibrationReading, error) {
	row := q.db.QueryRow(ctx, getCalibrationReadingForCalibration, arg.ID, arg.CalibrationID)
	var i CalibrationReading
	err := row.Scan(
		&i.ID,
		&i.CalibrationID,
		&i.Sequence,
		&i.ItemLabel,
		&i.ParameterKey,
		&i.Value,
		&i.Unit,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const listCalibrationReadings = `-- name: ListCalibrationReadings :many
SELECT id, calibration_id, sequence, item_label, parameter_key, value, unit, created_at, created_by, updated_by, updated_at FROM rtu.calibration_readings
WHERE calibration_id = $1::uuid
ORDER BY sequence
`

func (q *Queries) ListCalibrationReadings(ctx context.Context, calibrationID uuid.UUID) ([]CalibrationReading, error) {
	rows, err := q.db.Query(ctx, listCalibrationReadings, calibrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalibrationReading{}
	for rows.Next() {
		var i CalibrationReading
		if err := rows.Scan(
			&i.ID,
			&i.CalibrationID,
			&i.Sequence,
			&i.ItemLabel,
			&i.ParameterKey,
			&i.Value,
			&i.Unit,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCalibrationReadingsForCalibrations = `-- name: ListCalibrationReadingsForCalibrations :many
SELECT id, calibration_id, sequence, item_label, parameter_key, value, unit, created_at, created_by, updated_by, updated_at FROM rtu.calibration_readings
WHERE calibration_id = ANY ($1::uuid[])
ORDER BY calibration_id, sequence
`

func (q *Queries) ListCalibrationReadingsForCalibrations(ctx context.Context, calibrationIds []uuid.UUID) ([]CalibrationReading, error) {
	rows, err := q.db.Query(ctx, listCalibrationReadingsForCalibrations, calibrationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalibrationReading{}
	for rows.Next() {
		var i CalibrationReading
		if err := rows.Scan(
			&i.ID,
			&i.CalibrationID,
			&i.Sequence,
			&i.ItemLabel,
			&i.ParameterKey,
			&i.Value,
			&i.Unit,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextCalibrationReadingSequence = `-- name: NextCalibrationReadingSequence :one
SELECT (COALESCE(max(sequence), 0) + 1)::smallint AS next_sequence
FROM rtu.calibration_readings
WHERE calibration_id = $1::uuid
`

func (q *Queries) NextCalibrationReadingSequence(ctx context.Context, calibrationID uuid.UUID) (int16, error) {
	row := q.db.QueryRow(ctx, nextCalibrationReadingSequence, calibrationID)
	var next_sequence int16
	err := row.Scan(&next_sequence)
	return next_sequence, err
}

const updateCalibrationReading = `-- name: UpdateCalibrationReading :one
UPDATE rtu.calibration_readings SET
    sequence      = CASE WHEN $1::boolean THEN $2::smallint ELSE sequence END,
    item_label    = CASE WHEN $3::boolean THEN $4::varchar ELSE item_label END,
    parameter_key = CASE WHEN $5::boolean THEN $6::varchar ELSE parameter_key END,
    value         = CASE WHEN $7::boolean THEN $8::numeric ELSE value END,
    unit          = CASE WHEN $9::boolean THEN $10::varchar ELSE unit END,
    updated_by    = $11::uuid
WHERE id = $12::uuid
RETURNING id, calibration_id, sequence, item_label, parameter_key, value, unit, created_at, created_by, updated_by, updated_at
`

type UpdateCalibrationReadingParams struct {
	SequenceDoUpdate     bool             `db:"sequence_do_update" json:"sequence_do_update"`
	Sequence             int16            `db:"sequence" json:"sequence"`
	ItemLabelDoUpdate    bool             `db:"item_label_do_update" json:"item_label_do_update"`
	ItemLabel            *string          `db:"item_label" json:"item_label"`
	ParameterKeyDoUpdate bool             `db:"parameter_key_do_update" json:"parameter_key_do_update"`
	ParameterKey         string           `db:"parameter_key" json:"parameter_key"`
	ValueDoUpdate        bool             `db:"value_do_update" json:"value_do_update"`
	Value                *decimal.Decimal `db:"value" json:"value"`
	UnitDoUpdate         bool             `db:"unit_do_update" json:"unit_do_update"`
	Unit                 *string          `db:"unit" json:"unit"`
	UpdatedBy            *uuid.UUID       `db:"updated_by" json:"updated_by"`
	ID                   uuid.UUID        `db:"id" json:"id"`
}

func (q *Queries) UpdateCalibrationReading(ctx context.Context, arg UpdateCalibrationReadingParams) (CalibrationReading, error) {
	row := q.db.QueryRow(ctx, updateCalibrationReading,
		arg.SequenceDoUpdate,
		arg.Sequence,
		arg.ItemLabelDoUpdate,
		arg.ItemLabel,
		arg.ParameterKeyDoUpdate,
		arg.ParameterKey,
		arg.ValueDoUpdate,
		arg.Value,
		arg.UnitDoUpdate,
		arg.Unit,
		arg.UpdatedBy,
		arg.ID,
	)
	var i CalibrationReading
	err := row.Scan(
		&i.ID,
		&i.CalibrationID,
		&i.Sequence,
		&i.ItemLabel,
		&i.ParameterKey,
		&i.Value,
		&i.Unit,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
