// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checklist_items.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createChecklistItem = `-- name: CreateChecklistItem :one
INSERT INTO rtu.checklist_items (code, name, action_type, applicable_pm, sort_order, active, created_by, updated_by)
VALUES (
    $1::varchar,
    $2::varchar,
    $3::varchar,
    COALESCE($4::varchar, 'BOTH'),
    $5::smallint,
    COALESCE($6::boolean, true),
    $7::uuid,
    $8::uuid
)
RETURNING id, code, name, action_type, applicable_pm, sort_order, active, created_at, updated_at, created_by, updated_by
`

type CreateChecklistItemParams struct {
	Code         string     `db:"code" json:"code"`
	Name         string     `db:"name" json:"name"`
	ActionType   string     `db:"action_type" json:"action_type"`
	ApplicablePm *string    `db:"applicable_pm" json:"applicable_pm"`
	SortOrder    int16      `db:"sort_order" json:"sort_order"`
	Active       *bool      `db:"active" json:"active"`
	CreatedBy    *uuid.UUID `db:"created_by" json:"created_by"`
	UpdatedBy    *uuid.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) CreateChecklistItem(ctx context.Context, arg CreateChecklistItemParams) (ChecklistItem, error) {
	row := q.db.QueryRow(ctx, createChecklistItem,
		arg.Code,
		arg.Name,
		arg.ActionType,
		arg.ApplicablePm,
		arg.SortOrder,
		arg.Active,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i ChecklistItem
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.ActionType,
		&i.ApplicablePm,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteChecklistItem = `-- name: DeleteChecklistItem :execrows
DELETE FROM rtu.checklist_items WHERE id = $1::uuid
`

func (q *Queries) DeleteChecklistItem(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChecklistItem, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChecklistItem = `-- name: GetChecklistItem :one
SELECT id, code, name, action_type, applicable_pm, sort_order, active, created_at, updated_at, created_by, updated_by FROM rtu.checklist_items WHERE id = $1::uuid
`

func (q *Queries) GetChecklistItem(ctx context.Context, id uuid.UUID) (ChecklistItem, error) {
	row := q.db.QueryRow(ctx, getChecklistItem, id)
	var i ChecklistItem
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.ActionType,
		&i.ApplicablePm,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getChecklistItemByCode = `-- name: GetChecklistItemByCode :one
SELECT id, code, name, action_type, applicable_pm, sort_order, active, created_at, updated_at, created_by, updated_by FROM rtu.checklist_items WHERE code = $1::varchar
`

func (q *Queries) GetChecklistItemByCode(ctx context.Context, code string) (ChecklistItem, error) {
	row := q.db.QueryRow(ctx, getChecklistItemByCode, code)
	var i ChecklistItem
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.ActionType,
		&i.ApplicablePm,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const listChecklistItems = `-- name: ListChecklistItems :many
SELECT id, code, name, action_type, applicable_pm, sort_order, active, created_at, updated_at, created_by, updated_by FROM rtu.checklist_items
WHERE ($1::boolean IS NULL OR active = $1::boolean)
ORDER BY sort_order ASC
`

func (q *Queries) ListChecklistItems(ctx context.Context, activeFilter *bool) ([]ChecklistItem, error) {
	rows, err := q.db.Query(ctx, listChecklistItems, activeFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChecklistItem{}
	for rows.Next() {
		var i ChecklistItem
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.ActionType,
			&i.ApplicablePm,
			&i.SortOrder,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setChecklistItemActive = `-- name: SetChecklistItemActive :one
UPDATE rtu.checklist_items SET
    active     = $1::boolean,
    updated_by = $2::uuid
WHERE id = $3::uuid
RETURNING id, code, name, action_type, applicable_pm, sort_order, active, created_at, updated_at, created_by, updated_by
`

type SetChecklistItemActiveParams struct {
	Active    bool       `db:"active" json:"active"`
	UpdatedBy *uuid.UUID `db:"updated_by" json:"updated_by"`
	ID        uuid.UUID  `db:"id" json:"id"`
}

func (q *Queries) SetChecklistItemActive(ctx context.Context, arg SetChecklistItemActiveParams) (ChecklistItem, error) {
	row := q.db.QueryRow(ctx, setChecklistItemActive, arg.Active, arg.UpdatedBy, arg.ID)
	var i ChecklistItem
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.ActionType,
		&i.ApplicablePm,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const updateChecklistItem = `-- name: UpdateChecklistItem :one
UPDATE rtu.checklist_items SET
    code          = CASE WHEN $1::boolean THEN $2::varchar ELSE code END,
    name          = CASE WHEN $3::boolean THEN $4::varchar ELSE name END,
    action_type   = CASE WHEN $5::boolean THEN $6::varchar ELSE action_type END,
    applicable_pm = CASE WHEN $7::boolean THEN $8::varchar ELSE applicable_pm END,
    sort_order    = CASE WHEN $9::boolean THEN $10::smallint ELSE sort_order END,
    active        = CASE WHEN $11::boolean THEN $12::boolean ELSE active END,
    updated_by    = $13::uuid
WHERE id = $14::uuid
RETURNING id, code, name, action_type, applicable_pm, sort_order, active, created_at, updated_at, created_by, updated_by
`

type UpdateChecklistItemParams struct {
	CodeDoUpdate         bool       `db:"code_do_update" json:"code_do_update"`
	Code                 string     `db:"code" json:"code"`
	NameDoUpdate         bool       `db:"name_do_update" json:"name_do_update"`
	Name                 string     `db:"name" json:"name"`
	ActionTypeDoUpdate   bool       `db:"action_type_do_update" json:"action_type_do_update"`
	ActionType           string     `db:"action_type" json:"action_type"`
	ApplicablePmDoUpdate bool       `db:"applicable_pm_do_update" json:"applicable_pm_do_update"`
	ApplicablePm         string     `db:"applicable_pm" json:"applicable_pm"`
	SortOrderDoUpdate    bool       `db:"sort_order_do_update" json:"sort_order_do_update"`
	SortOrder            int16      `db:"sort_order" json:"sort_order"`
	ActiveDoUpdate       bool       `db:"active_do_update" json:"active_do_update"`
	Active               bool       `db:"active" json:"active"`
	UpdatedBy            *uuid.UUID `db:"updated_by" json:"updated_by"`
	ID                   uuid.UUID  `db:"id" json:"id"`
}

func (q *Queries) UpdateChecklistItem(ctx context.Context, arg UpdateChecklistItemParams) (ChecklistItem, error) {
	row := q.db.QueryRow(ctx, updateChecklistItem,
		arg.CodeDoUpdate,
		arg.Code,
		arg.NameDoUpdate,
		arg.Name,
		arg.ActionTypeDoUpdate,
		arg.ActionType,
		arg.ApplicablePmDoUpdate,
		arg.ApplicablePm,
		arg.SortOrderDoUpdate,
		arg.SortOrder,
		arg.ActiveDoUpdate,
		arg.Active,
		arg.UpdatedBy,
		arg.ID,
	)
	var i ChecklistItem
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.ActionType,
		&i.ApplicablePm,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
