// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cm_reports.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cmReportExists = `-- name: CmReportExists :one
SELECT EXISTS (SELECT 1 FROM rtu.cm_reports WHERE id = $1::uuid) AS found
`

func (q *Queries) CmReportExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, cmReportExists, id)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const createCmReport = `-- name: CreateCmReport :one
INSERT INTO rtu.cm_reports (
    work_order_id, work_order_round_id, pm_report_id, panel_id, panel_device_id,
    reported_by, tag_code, error_logs, problem_detail, root_cause, reference_info,
    corrective_action, recommendation, pending_reason, repaired_by,
    reported_at, started_at, ended_at, created_by, updated_by
)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4::uuid,
    $5::uuid,
    $6::uuid,
    $7::varchar,
    $8::text,
    $9::text,
    $10::text,
    $11::text,
    $12::text,
    $13::text,
    $14::text,
    $15::uuid,
    $16::timestamptz,
    $17::timestamptz,
    $18::timestamptz,
    $19::uuid,
    $20::uuid
)
RETURNING id, work_order_id, work_order_round_id, pm_report_id, panel_id, panel_device_id, reported_by, tag_code, error_logs, problem_detail, root_cause, reference_info, corrective_action, recommendation, pending_reason, repaired_by, reported_at, started_at, ended_at, created_at, updated_at, created_by, updated_by
`

type CreateCmReportParams struct {
	WorkOrderID      *uuid.UUID `db:"work_order_id" json:"work_order_id"`
	WorkOrderRoundID *uuid.UUID `db:"work_order_round_id" json:"work_order_round_id"`
	PmReportID       *uuid.UUID `db:"pm_report_id" json:"pm_report_id"`
	PanelID          uuid.UUID  `db:"panel_id" json:"panel_id"`
	PanelDeviceID    *uuid.UUID `db:"panel_device_id" json:"panel_device_id"`
	ReportedBy       uuid.UUID  `db:"reported_by" json:"reported_by"`
	TagCode          *string    `db:"tag_code" json:"tag_code"`
	ErrorLogs        *string    `db:"error_logs" json:"error_logs"`
	ProblemDetail    *string    `db:"problem_detail" json:"problem_detail"`
	RootCause        *string    `db:"root_cause" json:"root_cause"`
	ReferenceInfo    *string    `db:"reference_info" json:"reference_info"`
	CorrectiveAction *string    `db:"corrective_action" json:"corrective_action"`
	Recommendation   *string    `db:"recommendation" json:"recommendation"`
	PendingReason    *string    `db:"pending_reason" json:"pending_reason"`
	RepairedBy       *uuid.UUID `db:"repaired_by" json:"repaired_by"`
	ReportedAt       *time.Time `db:"reported_at" json:"reported_at"`
	StartedAt        *time.Time `db:"started_at" json:"started_at"`
	EndedAt          *time.Time `db:"ended_at" json:"ended_at"`
	CreatedBy        *uuid.UUID `db:"created_by" json:"created_by"`
	UpdatedBy        *uuid.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) CreateCmReport(ctx context.Context, arg CreateCmReportParams) (CmReport, error) {
	row := q.db.QueryRow(ctx, createCmReport,
		arg.WorkOrderID,
		arg.WorkOrderRoundID,
		arg.PmReportID,
		arg.PanelID,
		arg.PanelDeviceID,
		arg.ReportedBy,
		arg.TagCode,
		arg.ErrorLogs,
		arg.ProblemDetail,
		arg.RootCause,
		arg.ReferenceInfo,
		arg.CorrectiveAction,
		arg.Recommendation,
		arg.PendingReason,
		arg.RepairedBy,
		arg.ReportedAt,
		arg.StartedAt,
		arg.EndedAt,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i CmReport
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.WorkOrderRoundID,
		&i.PmReportID,
		&i.PanelID,
		&i.PanelDeviceID,
		&i.ReportedBy,
		&i.TagCode,
		&i.ErrorLogs,
		&i.ProblemDetail,
		&i.RootCause,
		&i.ReferenceInfo,
		&i.CorrectiveAction,
		&i.Recommendation,
		&i.PendingReason,
		&i.RepairedBy,
		&i.ReportedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteCmReport = `-- name: DeleteCmReport :execrows
DELETE FROM rtu.cm_reports WHERE id = $1::uuid
`

func (q *Queries) DeleteCmReport(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCmReport, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCmReport = `-- name: GetCmReport :one
SELECT id, work_order_id, work_order_round_id, pm_report_id, panel_id, panel_device_id, reported_by, tag_code, error_logs, problem_detail, root_cause, reference_info, corrective_action, recommendation, pending_reason, repaired_by, reported_at, started_at, ended_at, created_at, updated_at, created_by, updated_by FROM rtu.cm_reports WHERE id = $1::uuid
`

func (q *Queries) GetCmReport(ctx context.Context, id uuid.UUID) (CmReport, error) {
	row := q.db.QueryRow(ctx, getCmReport, id)
	var i CmReport
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.WorkOrderRoundID,
		&i.PmReportID,
		&i.PanelID,
		&i.PanelDeviceID,
		&i.ReportedBy,
		&i.TagCode,
		&i.ErrorLogs,
		&i.ProblemDetail,
		&i.RootCause,
		&i.ReferenceInfo,
		&i.CorrectiveAction,
		&i.Recommendation,
		&i.PendingReason,
		&i.RepairedBy,
		&i.ReportedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getCmReportByRound = `-- name: GetCmReportByRound :one
SELECT id, work_order_id, work_order_round_id, pm_report_id, panel_id, panel_device_id, reported_by, tag_code, error_logs, problem_detail, root_cause, reference_info, corrective_action, recommendation, pending_reason, repaired_by, reported_at, started_at, ended_at, created_at, updated_at, created_by, updated_by FROM rtu.cm_reports WHERE work_order_round_id = $1::uuid
`

func (q *Queries) GetCmReportByRound(ctx context.Context, workOrderRoundID uuid.UUID) (CmReport, error) {
	row := q.db.QueryRow(ctx, getCmReportByRound, workOrderRoundID)
	var i CmReport
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.WorkOrderRoundID,
		&i.PmReportID,
		&i.PanelID,
		&i.PanelDeviceID,
		&i.ReportedBy,
		&i.TagCode,
		&i.ErrorLogs,
		&i.ProblemDetail,
		&i.RootCause,
		&i.ReferenceInfo,
		&i.CorrectiveAction,
		&i.Recommendation,
		&i.PendingReason,
		&i.RepairedBy,
		&i.ReportedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const listCmReportsByPmReport = `-- name: ListCmReportsByPmReport :many
SELECT id, work_order_id, work_order_round_id, pm_report_id, panel_id, panel_device_id, reported_by, tag_code, error_logs, problem_detail, root_cause, reference_info, corrective_action, recommendation, pending_reason, repaired_by, reported_at, started_at, ended_at, created_at, updated_at, created_by, updated_by FROM rtu.cm_reports WHERE pm_report_id = $1::uuid ORDER BY created_at
`

func (q *Queries) ListCmReportsByPmReport(ctx context.Context, pmReportID uuid.UUID) ([]CmReport, error) {
	rows, err := q.db.Query(ctx, listCmReportsByPmReport, pmReportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CmReport{}
	for rows.Next() {
		var i CmReport
		if err := rows.Scan(
			&i.ID,
			&i.WorkOrderID,
			&i.WorkOrderRoundID,
			&i.PmReportID,
			&i.PanelID,
			&i.PanelDeviceID,
			&i.ReportedBy,
			&i.TagCode,
			&i.ErrorLogs,
			&i.ProblemDetail,
			&i.RootCause,
			&i.ReferenceInfo,
			&i.CorrectiveAction,
			&i.Recommendation,
			&i.PendingReason,
			&i.RepairedBy,
			&i.ReportedAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCmReport = `-- name: UpdateCmReport :one
UPDATE rtu.cm_reports SET
    panel_device_id   = CASE WHEN $1::boolean THEN $2::uuid ELSE panel_device_id END,
    tag_code          = CASE WHEN $3::boolean THEN $4::varchar ELSE tag_code END,
    error_logs        = CASE WHEN $5::boolean THEN $6::text ELSE error_logs END,
    problem_detail    = CASE WHEN $7::boolean THEN $8::text ELSE problem_detail END,
    root_cause        = CASE WHEN $9::boolean THEN $10::text ELSE root_cause END,
    reference_info    = CASE WHEN $11::boolean THEN $12::text ELSE reference_info END,
    corrective_action = CASE WHEN $13::boolean THEN $14::text ELSE corrective_action END,
    recommendation    = CASE WHEN $15::boolean THEN $16::text ELSE recommendation END,
    pending_reason    = CASE WHEN $17::boolean THEN $18::text ELSE pending_reason END,
    repaired_by       = CASE WHEN $19::boolean THEN $20::uuid ELSE repaired_by END,
    reported_at       = CASE WHEN $21::boolean THEN $22::timestamptz ELSE reported_at END,
    started_at        = CASE WHEN $23::boolean THEN $24::timestamptz ELSE started_at END,
    ended_at          = CASE WHEN $25::boolean THEN $26::timestamptz ELSE ended_at END,
    updated_by        = $27::uuid
WHERE id = $28::uuid
RETURNING id, work_order_id, work_order_round_id, pm_report_id, panel_id, panel_device_id, reported_by, tag_code, error_logs, problem_detail, root_cause, reference_info, corrective_action, recommendation, pending_reason, repaired_by, reported_at, started_at, ended_at, created_at, updated_at, created_by, updated_by
`

type UpdateCmReportParams struct {
	PanelDeviceIDDoUpdate    bool       `db:"panel_device_id_do_update" json:"panel_device_id_do_update"`
	PanelDeviceID            *uuid.UUID `db:"panel_device_id" json:"panel_device_id"`
	TagCodeDoUpdate          bool       `db:"tag_code_do_update" json:"tag_code_do_update"`
	TagCode                  *string    `db:"tag_code" json:"tag_code"`
	ErrorLogsDoUpdate        bool       `db:"error_logs_do_update" json:"error_logs_do_update"`
	ErrorLogs                *string    `db:"error_logs" json:"error_logs"`
	ProblemDetailDoUpdate    bool       `db:"problem_detail_do_update" json:"problem_detail_do_update"`
	ProblemDetail            *string    `db:"problem_detail" json:"problem_detail"`
	RootCauseDoUpdate        bool       `db:"root_cause_do_update" json:"root_cause_do_update"`
	RootCause                *string    `db:"root_cause" json:"root_cause"`
	ReferenceInfoDoUpdate    bool       `db:"reference_info_do_update" json:"reference_info_do_update"`
	ReferenceInfo            *string    `db:"reference_info" json:"reference_info"`
	CorrectiveActionDoUpdate bool       `db:"corrective_action_do_update" json:"corrective_action_do_update"`
	CorrectiveAction         *string    `db:"corrective_action" json:"corrective_action"`
	RecommendationDoUpdate   bool       `db:"recommendation_do_update" json:"recommendation_do_update"`
	Recommendation           *string    `db:"recommendation" json:"recommendation"`
	PendingReasonDoUpdate    bool       `db:"pending_reason_do_update" json:"pending_reason_do_update"`
	PendingReason            *string    `db:"pending_reason" json:"pending_reason"`
	RepairedByDoUpdate       bool       `db:"repaired_by_do_update" json:"repaired_by_do_update"`
	RepairedBy               *uuid.UUID `db:"repaired_by" json:"repaired_by"`
	ReportedAtDoUpdate       bool       `db:"reported_at_do_update" json:"reported_at_do_update"`
	ReportedAt               *time.Time `db:"reported_at" json:"reported_at"`
	StartedAtDoUpdate        bool       `db:"started_at_do_update" json:"started_at_do_update"`
	StartedAt                *time.Time `db:"started_at" json:"started_at"`
	EndedAtDoUpdate          bool       `db:"ended_at_do_update" json:"ended_at_do_update"`
	EndedAt                  *time.Time `db:"ended_at" json:"ended_at"`
	UpdatedBy                *uuid.UUID `db:"updated_by" json:"updated_by"`
	ID                       uuid.UUID  `db:"id" json:"id"`
}

func (q *Queries) UpdateCmReport(ctx context.Context, arg UpdateCmReportParams) (CmReport, error) {
	row := q.db.QueryRow(ctx, updateCmReport,
		arg.PanelDeviceIDDoUpdate,
		arg.PanelDeviceID,
		arg.TagCodeDoUpdate,
		arg.TagCode,
		arg.ErrorLogsDoUpdate,
		arg.ErrorLogs,
		arg.ProblemDetailDoUpdate,
		arg.ProblemDetail,
		arg.RootCauseDoUpdate,
		arg.RootCause,
		arg.ReferenceInfoDoUpdate,
		arg.ReferenceInfo,
		arg.CorrectiveActionDoUpdate,
		arg.CorrectiveAction,
		arg.RecommendationDoUpdate,
		arg.Recommendation,
		arg.PendingReasonDoUpdate,
		arg.PendingReason,
		arg.RepairedByDoUpdate,
		arg.RepairedBy,
		arg.ReportedAtDoUpdate,
		arg.ReportedAt,
		arg.StartedAtDoUpdate,
		arg.StartedAt,
		arg.EndedAtDoUpdate,
		arg.EndedAt,
		arg.UpdatedBy,
		arg.ID,
	)
	var i CmReport
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.WorkOrderRoundID,
		&i.PmReportID,
		&i.PanelID,
		&i.PanelDeviceID,
		&i.ReportedBy,
		&i.TagCode,
		&i.ErrorLogs,
		&i.ProblemDetail,
		&i.RootCause,
		&i.ReferenceInfo,
		&i.CorrectiveAction,
		&i.Recommendation,
		&i.PendingReason,
		&i.RepairedBy,
		&i.ReportedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
