// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForBulkCreateCalibrationReadings implements pgx.CopyFromSource.
type iteratorForBulkCreateCalibrationReadings struct {
	rows                 []BulkCreateCalibrationReadingsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkCreateCalibrationReadings) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkCreateCalibrationReadings) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].CalibrationID,
		r.rows[0].Sequence,
		r.rows[0].ItemLabel,
		r.rows[0].ParameterKey,
		r.rows[0].Value,
		r.rows[0].Unit,
		r.rows[0].CreatedBy,
	}, nil
}

func (r iteratorForBulkCreateCalibrationReadings) Err() error {
	return nil
}

func (q *Queries) BulkCreateCalibrationReadings(ctx context.Context, arg []BulkCreateCalibrationReadingsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"rtu", "calibration_readings"}, []string{"calibration_id", "sequence", "item_label", "parameter_key", "value", "unit", "created_by"}, &iteratorForBulkCreateCalibrationReadings{rows: arg})
}

// iteratorForBulkCreateChecklistResults implements pgx.CopyFromSource.
type iteratorForBulkCreateChecklistResults struct {
	rows                 []BulkCreateChecklistResultsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkCreateChecklistResults) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkCreateChecklistResults) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].PmReportID,
		r.rows[0].ChecklistItemID,
		r.rows[0].PanelDeviceID,
		r.rows[0].Status,
		r.rows[0].Value,
		r.rows[0].MeterNo,
		r.rows[0].Note,
		r.rows[0].CheckedBy,
		r.rows[0].CheckedAt,
		r.rows[0].CreatedBy,
	}, nil
}

func (r iteratorForBulkCreateChecklistResults) Err() error {
	return nil
}

func (q *Queries) BulkCreateChecklistResults(ctx context.Context, arg []BulkCreateChecklistResultsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"rtu", "checklist_results"}, []string{"pm_report_id", "checklist_item_id", "panel_device_id", "status", "value", "meter_no", "note", "checked_by", "checked_at", "created_by"}, &iteratorForBulkCreateChecklistResults{rows: arg})
}

// iteratorForBulkCreatePmPowerTestPoints implements pgx.CopyFromSource.
type iteratorForBulkCreatePmPowerTestPoints struct {
	rows                 []BulkCreatePmPowerTestPointsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkCreatePmPowerTestPoints) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkCreatePmPowerTestPoints) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].PmPowerTestID,
		r.rows[0].EquipmentRole,
		r.rows[0].Brand,
		r.rows[0].Model,
		r.rows[0].InputAcceptRange,
		r.rows[0].InputResultValue,
		r.rows[0].InputUnit,
		r.rows[0].OutputAcceptRange,
		r.rows[0].OutputResultValue,
		r.rows[0].OutputUnit,
		r.rows[0].Result,
		r.rows[0].CorrectiveAction,
		r.rows[0].CreatedBy,
	}, nil
}

func (r iteratorForBulkCreatePmPowerTestPoints) Err() error {
	return nil
}

func (q *Queries) BulkCreatePmPowerTestPoints(ctx context.Context, arg []BulkCreatePmPowerTestPointsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"rtu", "pm_power_test_points"}, []string{"pm_power_test_id", "equipment_role", "brand", "model", "input_accept_range", "input_result_value", "input_unit", "output_accept_range", "output_result_value", "output_unit", "result", "corrective_action", "created_by"}, &iteratorForBulkCreatePmPowerTestPoints{rows: arg})
}
