// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: engineers.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createEngineer = `-- name: CreateEngineer :one
INSERT INTO rtu.engineers (full_name, license_no, position, active, created_by, updated_by)
VALUES (
    $1::varchar,
    $2::varchar,
    $3::varchar,
    COALESCE($4::boolean, true),
    $5::uuid,
    $6::uuid
)
RETURNING id, full_name, license_no, position, active, created_at, updated_at, created_by, updated_by
`

type CreateEngineerParams struct {
	FullName  string     `db:"full_name" json:"full_name"`
	LicenseNo *string    `db:"license_no" json:"license_no"`
	Position  *string    `db:"position" json:"position"`
	Active    *bool      `db:"active" json:"active"`
	CreatedBy *uuid.UUID `db:"created_by" json:"created_by"`
	UpdatedBy *uuid.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) CreateEngineer(ctx context.Context, arg CreateEngineerParams) (Engineer, error) {
	row := q.db.QueryRow(ctx, createEngineer,
		arg.FullName,
		arg.LicenseNo,
		arg.Position,
		arg.Active,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Engineer
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.LicenseNo,
		&i.Position,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteEngineer = `-- name: DeleteEngineer :execrows
DELETE FROM rtu.engineers WHERE id = $1::uuid
`

func (q *Queries) DeleteEngineer(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEngineer, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const engineerExists = `-- name: EngineerExists :one
SELECT EXISTS (SELECT 1 FROM rtu.engineers WHERE id = $1::uuid) AS found
`

func (q *Queries) EngineerExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, engineerExists, id)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const getEngineer = `-- name: GetEngineer :one
SELECT id, full_name, license_no, position, active, created_at, updated_at, created_by, updated_by FROM rtu.engineers WHERE id = $1::uuid
`

func (q *Queries) GetEngineer(ctx context.Context, id uuid.UUID) (Engineer, error) {
	row := q.db.QueryRow(ctx, getEngineer, id)
	var i Engineer
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.LicenseNo,
		&i.Position,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const setEngineerActive = `-- name: SetEngineerActive :one
UPDATE rtu.engineers SET
    active     = $1::boolean,
    updated_by = $2::uuid
WHERE id = $3::uuid
RETURNING id, full_name, license_no, position, active, created_at, updated_at, created_by, updated_by
`

type SetEngineerActiveParams struct {
	Active    bool       `db:"active" json:"active"`
	UpdatedBy *uuid.UUID `db:"updated_by" json:"updated_by"`
	ID        uuid.UUID  `db:"id" json:"id"`
}

func (q *Queries) SetEngineerActive(ctx context.Context, arg SetEngineerActiveParams) (Engineer, error) {
	row := q.db.QueryRow(ctx, setEngineerActive, arg.Active, arg.UpdatedBy, arg.ID)
	var i Engineer
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.LicenseNo,
		&i.Position,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const updateEngineer = `-- name: UpdateEngineer :one
UPDATE rtu.engineers SET
    full_name  = CASE WHEN $1::boolean THEN $2::varchar ELSE full_name END,
    license_no = CASE WHEN $3::boolean THEN $4::varchar ELSE license_no END,
    position   = CASE WHEN $5::boolean THEN $6::varchar ELSE position END,
    active     = CASE WHEN $7::boolean THEN $8::boolean ELSE active END,
    updated_by = $9::uuid
WHERE id = $10::uuid
RETURNING id, full_name, license_no, position, active, created_at, updated_at, created_by, updated_by
`

type UpdateEngineerParams struct {
	FullNameDoUpdate  bool       `db:"full_name_do_update" json:"full_name_do_update"`
	FullName          string     `db:"full_name" json:"full_name"`
	LicenseNoDoUpdate bool       `db:"license_no_do_update" json:"license_no_do_update"`
	LicenseNo         *string    `db:"license_no" json:"license_no"`
	PositionDoUpdate  bool       `db:"position_do_update" json:"position_do_update"`
	Position          *string    `db:"position" json:"position"`
	ActiveDoUpdate    bool       `db:"active_do_update" json:"active_do_update"`
	Active            bool       `db:"active" json:"active"`
	UpdatedBy         *uuid.UUID `db:"updated_by" json:"updated_by"`
	ID                uuid.UUID  `db:"id" json:"id"`
}

func (q *Queries) UpdateEngineer(ctx context.Context, arg UpdateEngineerParams) (Engineer, error) {
	row := q.db.QueryRow(ctx, updateEngineer,
		arg.FullNameDoUpdate,
		arg.FullName,
		arg.LicenseNoDoUpdate,
		arg.LicenseNo,
		arg.PositionDoUpdate,
		arg.Position,
		arg.ActiveDoUpdate,
		arg.Active,
		arg.UpdatedBy,
		arg.ID,
	)
	var i Engineer
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.LicenseNo,
		&i.Position,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
