// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/rtu-api/internal/httpx"
	"github.com/shopspring/decimal"
)

type Attachment struct {
	ID           uuid.UUID  `db:"id" json:"id"`
	EntityType   string     `db:"entity_type" json:"entity_type"`
	EntityID     uuid.UUID  `db:"entity_id" json:"entity_id"`
	S3Bucket     string     `db:"s3_bucket" json:"s3_bucket"`
	S3Key        string     `db:"s3_key" json:"s3_key"`
	OriginalName *string    `db:"original_name" json:"original_name"`
	MimeType     string     `db:"mime_type" json:"mime_type"`
	FileSize     int64      `db:"file_size" json:"file_size"`
	Caption      *string    `db:"caption" json:"caption"`
	CreatedBy    uuid.UUID  `db:"created_by" json:"created_by"`
	CreatedAt    time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time  `db:"updated_at" json:"updated_at"`
	UpdatedBy    *uuid.UUID `db:"updated_by" json:"updated_by"`
}

type Calibration struct {
	ID               uuid.UUID  `db:"id" json:"id"`
	PanelDeviceID    uuid.UUID  `db:"panel_device_id" json:"panel_device_id"`
	InstrumentID     uuid.UUID  `db:"instrument_id" json:"instrument_id"`
	PerformedBy      *string    `db:"performed_by" json:"performed_by"`
	PerformedAt      time.Time  `db:"performed_at" json:"performed_at"`
	Result           string     `db:"result" json:"result"`
	Remark           *string    `db:"remark" json:"remark"`
	CreatedAt        time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt        time.Time  `db:"updated_at" json:"updated_at"`
	CreatedBy        *uuid.UUID `db:"created_by" json:"created_by"`
	UpdatedBy        *uuid.UUID `db:"updated_by" json:"updated_by"`
	WorkOrderID      *uuid.UUID `db:"work_order_id" json:"work_order_id"`
	PmReportID       *uuid.UUID `db:"pm_report_id" json:"pm_report_id"`
	ChannelType      *string    `db:"channel_type" json:"channel_type"`
	EutManufacturer  *string    `db:"eut_manufacturer" json:"eut_manufacturer"`
	EutModel         *string    `db:"eut_model" json:"eut_model"`
	EutSerialNo      *string    `db:"eut_serial_no" json:"eut_serial_no"`
	EutInputRange    *string    `db:"eut_input_range" json:"eut_input_range"`
	EutAccuracyClass *string    `db:"eut_accuracy_class" json:"eut_accuracy_class"`
	EutPowerSupply   *string    `db:"eut_power_supply" json:"eut_power_supply"`
	EutOutputRange   *string    `db:"eut_output_range" json:"eut_output_range"`
	ResultType       *string    `db:"result_type" json:"result_type"`
	ResultOtherText  *string    `db:"result_other_text" json:"result_other_text"`
}

type CalibrationInstrument struct {
	ID              uuid.UUID   `db:"id" json:"id"`
	Name            string      `db:"name" json:"name"`
	Manufacturer    *string     `db:"manufacturer" json:"manufacturer"`
	Model           *string     `db:"model" json:"model"`
	SerialNumber    *string     `db:"serial_number" json:"serial_number"`
	CalibrationDate *httpx.Date `db:"calibration_date" json:"calibration_date"`
	ExpireDate      *httpx.Date `db:"expire_date" json:"expire_date"`
	Active          bool        `db:"active" json:"active"`
	CreatedAt       time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time   `db:"updated_at" json:"updated_at"`
	CreatedBy       *uuid.UUID  `db:"created_by" json:"created_by"`
	UpdatedBy       *uuid.UUID  `db:"updated_by" json:"updated_by"`
	EquipmentType   *string     `db:"equipment_type" json:"equipment_type"`
	Brand           *string     `db:"brand" json:"brand"`
}

type CalibrationReading struct {
	ID            uuid.UUID        `db:"id" json:"id"`
	CalibrationID uuid.UUID        `db:"calibration_id" json:"calibration_id"`
	Sequence      int16            `db:"sequence" json:"sequence"`
	ItemLabel     *string          `db:"item_label" json:"item_label"`
	ParameterKey  string           `db:"parameter_key" json:"parameter_key"`
	Value         *decimal.Decimal `db:"value" json:"value"`
	Unit          *string          `db:"unit" json:"unit"`
	CreatedAt     time.Time        `db:"created_at" json:"created_at"`
	CreatedBy     *uuid.UUID       `db:"created_by" json:"created_by"`
	UpdatedBy     *uuid.UUID       `db:"updated_by" json:"updated_by"`
	UpdatedAt     time.Time        `db:"updated_at" json:"updated_at"`
}

type ChecklistItem struct {
	ID           uuid.UUID  `db:"id" json:"id"`
	Code         string     `db:"code" json:"code"`
	Name         string     `db:"name" json:"name"`
	ActionType   string     `db:"action_type" json:"action_type"`
	ApplicablePm string     `db:"applicable_pm" json:"applicable_pm"`
	SortOrder    int16      `db:"sort_order" json:"sort_order"`
	Active       bool       `db:"active" json:"active"`
	CreatedAt    time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time  `db:"updated_at" json:"updated_at"`
	CreatedBy    *uuid.UUID `db:"created_by" json:"created_by"`
	UpdatedBy    *uuid.UUID `db:"updated_by" json:"updated_by"`
}

type ChecklistResult struct {
	ID              uuid.UUID  `db:"id" json:"id"`
	PmReportID      uuid.UUID  `db:"pm_report_id" json:"pm_report_id"`
	ChecklistItemID uuid.UUID  `db:"checklist_item_id" json:"checklist_item_id"`
	PanelDeviceID   *uuid.UUID `db:"panel_device_id" json:"panel_device_id"`
	Status          *string    `db:"status" json:"status"`
	Value           *string    `db:"value" json:"value"`
	MeterNo         *string    `db:"meter_no" json:"meter_no"`
	Note            *string    `db:"note" json:"note"`
	CheckedBy       *uuid.UUID `db:"checked_by" json:"checked_by"`
	CheckedAt       time.Time  `db:"checked_at" json:"checked_at"`
	CreatedAt       time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time  `db:"updated_at" json:"updated_at"`
	CreatedBy       *uuid.UUID `db:"created_by" json:"created_by"`
	UpdatedBy       *uuid.UUID `db:"updated_by" json:"updated_by"`
}

type CmReport struct {
	ID               uuid.UUID  `db:"id" json:"id"`
	WorkOrderID      *uuid.UUID `db:"work_order_id" json:"work_order_id"`
	WorkOrderRoundID *uuid.UUID `db:"work_order_round_id" json:"work_order_round_id"`
	PmReportID       *uuid.UUID `db:"pm_report_id" json:"pm_report_id"`
	PanelID          uuid.UUID  `db:"panel_id" json:"panel_id"`
	PanelDeviceID    *uuid.UUID `db:"panel_device_id" json:"panel_device_id"`
	ReportedBy       uuid.UUID  `db:"reported_by" json:"reported_by"`
	TagCode          *string    `db:"tag_code" json:"tag_code"`
	ErrorLogs        *string    `db:"error_logs" json:"error_logs"`
	ProblemDetail    *string    `db:"problem_detail" json:"problem_detail"`
	RootCause        *string    `db:"root_cause" json:"root_cause"`
	ReferenceInfo    *string    `db:"reference_info" json:"reference_info"`
	CorrectiveAction *string    `db:"corrective_action" json:"corrective_action"`
	Recommendation   *string    `db:"recommendation" json:"recommendation"`
	PendingReason    *string    `db:"pending_reason" json:"pending_reason"`
	RepairedBy       *uuid.UUID `db:"repaired_by" json:"repaired_by"`
	ReportedAt       *time.Time `db:"reported_at" json:"reported_at"`
	StartedAt        *time.Time `db:"started_at" json:"started_at"`
	EndedAt          *time.Time `db:"ended_at" json:"ended_at"`
	CreatedAt        time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt        time.Time  `db:"updated_at" json:"updated_at"`
	CreatedBy        *uuid.UUID `db:"created_by" json:"created_by"`
	UpdatedBy        *uuid.UUID `db:"updated_by" json:"updated_by"`
	ProblemTopicID   *uuid.UUID `db:"problem_topic_id" json:"problem_topic_id"`
}

type DeviceModel struct {
	ID            uuid.UUID   `db:"id" json:"id"`
	Code          string      `db:"code" json:"code"`
	Name          string      `db:"name" json:"name"`
	Manufacturer  *string     `db:"manufacturer" json:"manufacturer"`
	Model         *string     `db:"model" json:"model"`
	Description   *string     `db:"description" json:"description"`
	Active        bool        `db:"active" json:"active"`
	CreatedAt     time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time   `db:"updated_at" json:"updated_at"`
	CreatedBy     *uuid.UUID  `db:"created_by" json:"created_by"`
	UpdatedBy     *uuid.UUID  `db:"updated_by" json:"updated_by"`
	EquipmentType *string     `db:"equipment_type" json:"equipment_type"`
	Brand         *string     `db:"brand" json:"brand"`
	SerialNumber  *string     `db:"serial_number" json:"serial_number"`
	ExpireDate    *httpx.Date `db:"expire_date" json:"expire_date"`
}

type Engineer struct {
	ID        uuid.UUID  `db:"id" json:"id"`
	FullName  string     `db:"full_name" json:"full_name"`
	LicenseNo *string    `db:"license_no" json:"license_no"`
	Position  *string    `db:"position" json:"position"`
	Active    bool       `db:"active" json:"active"`
	CreatedAt time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt time.Time  `db:"updated_at" json:"updated_at"`
	CreatedBy *uuid.UUID `db:"created_by" json:"created_by"`
	UpdatedBy *uuid.UUID `db:"updated_by" json:"updated_by"`
}

type Notification struct {
	ID          uuid.UUID  `db:"id" json:"id"`
	WorkOrderID uuid.UUID  `db:"work_order_id" json:"work_order_id"`
	RecipientID uuid.UUID  `db:"recipient_id" json:"recipient_id"`
	Type        string     `db:"type" json:"type"`
	Title       *string    `db:"title" json:"title"`
	Message     *string    `db:"message" json:"message"`
	IsRead      bool       `db:"is_read" json:"is_read"`
	ReadAt      *time.Time `db:"read_at" json:"read_at"`
	CreatedAt   time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time  `db:"updated_at" json:"updated_at"`
	CreatedBy   *uuid.UUID `db:"created_by" json:"created_by"`
	UpdatedBy   *uuid.UUID `db:"updated_by" json:"updated_by"`
}

type Panel struct {
	ID          uuid.UUID        `db:"id" json:"id"`
	Code        string           `db:"code" json:"code"`
	Location    *string          `db:"location" json:"location"`
	Latitude    *decimal.Decimal `db:"latitude" json:"latitude"`
	Longitude   *decimal.Decimal `db:"longitude" json:"longitude"`
	Active      bool             `db:"active" json:"active"`
	CreatedAt   time.Time        `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time        `db:"updated_at" json:"updated_at"`
	CreatedBy   *uuid.UUID       `db:"created_by" json:"created_by"`
	UpdatedBy   *uuid.UUID       `db:"updated_by" json:"updated_by"`
	InstallDate *httpx.Date      `db:"install_date" json:"install_date"`
	LastPmDate  *httpx.Date      `db:"last_pm_date" json:"last_pm_date"`
	NextPmDate  *httpx.Date      `db:"next_pm_date" json:"next_pm_date"`
}

type PanelDevice struct {
	ID                  uuid.UUID   `db:"id" json:"id"`
	PanelID             uuid.UUID   `db:"panel_id" json:"panel_id"`
	TagName             *string     `db:"tag_name" json:"tag_name"`
	SerialNumber        *string     `db:"serial_number" json:"serial_number"`
	AssetCode           *string     `db:"asset_code" json:"asset_code"`
	FirmwareVersion     *string     `db:"firmware_version" json:"firmware_version"`
	CommunicationStatus string      `db:"communication_status" json:"communication_status"`
	HealthStatus        string      `db:"health_status" json:"health_status"`
	InstalledAt         *httpx.Date `db:"installed_at" json:"installed_at"`
	LastSeenAt          *time.Time  `db:"last_seen_at" json:"last_seen_at"`
	Note                *string     `db:"note" json:"note"`
	Active              bool        `db:"active" json:"active"`
	CreatedAt           time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt           time.Time   `db:"updated_at" json:"updated_at"`
	CreatedBy           *uuid.UUID  `db:"created_by" json:"created_by"`
	UpdatedBy           *uuid.UUID  `db:"updated_by" json:"updated_by"`
	Name                string      `db:"name" json:"name"`
	EquipmentType       *string     `db:"equipment_type" json:"equipment_type"`
	Manufacturer        *string     `db:"manufacturer" json:"manufacturer"`
	Brand               *string     `db:"brand" json:"brand"`
	Model               *string     `db:"model" json:"model"`
	CalibrationDate     *httpx.Date `db:"calibration_date" json:"calibration_date"`
	ExpireDate          *httpx.Date `db:"expire_date" json:"expire_date"`
}

type PanelImage struct {
	ID           uuid.UUID  `db:"id" json:"id"`
	PanelID      uuid.UUID  `db:"panel_id" json:"panel_id"`
	ImageType    string     `db:"image_type" json:"image_type"`
	S3Bucket     string     `db:"s3_bucket" json:"s3_bucket"`
	S3Key        string     `db:"s3_key" json:"s3_key"`
	OriginalName *string    `db:"original_name" json:"original_name"`
	MimeType     string     `db:"mime_type" json:"mime_type"`
	FileSize     int64      `db:"file_size" json:"file_size"`
	Caption      *string    `db:"caption" json:"caption"`
	SortOrder    int16      `db:"sort_order" json:"sort_order"`
	Active       bool       `db:"active" json:"active"`
	CreatedAt    time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time  `db:"updated_at" json:"updated_at"`
	CreatedBy    *uuid.UUID `db:"created_by" json:"created_by"`
	UpdatedBy    *uuid.UUID `db:"updated_by" json:"updated_by"`
}

type PmGroundTest struct {
	ID           uuid.UUID        `db:"id" json:"id"`
	PmReportID   uuid.UUID        `db:"pm_report_id" json:"pm_report_id"`
	ResistanceLg *decimal.Decimal `db:"resistance_lg" json:"resistance_lg"`
	ResistanceNg *decimal.Decimal `db:"resistance_ng" json:"resistance_ng"`
	VoltageLg    *decimal.Decimal `db:"voltage_lg" json:"voltage_lg"`
	VoltageNg    *decimal.Decimal `db:"voltage_ng" json:"voltage_ng"`
	Result       *string          `db:"result" json:"result"`
	Note         *string          `db:"note" json:"note"`
	MeasuredBy   *uuid.UUID       `db:"measured_by" json:"measured_by"`
	MeasuredAt   *time.Time       `db:"measured_at" json:"measured_at"`
	CreatedAt    time.Time        `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time        `db:"updated_at" json:"updated_at"`
	CreatedBy    *uuid.UUID       `db:"created_by" json:"created_by"`
	UpdatedBy    *uuid.UUID       `db:"updated_by" json:"updated_by"`
}

type PmPowerTest struct {
	ID           uuid.UUID  `db:"id" json:"id"`
	PmReportID   uuid.UUID  `db:"pm_report_id" json:"pm_report_id"`
	InstrumentID *uuid.UUID `db:"instrument_id" json:"instrument_id"`
	TestedBy     *uuid.UUID `db:"tested_by" json:"tested_by"`
	TestedAt     *time.Time `db:"tested_at" json:"tested_at"`
	CreatedAt    time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time  `db:"updated_at" json:"updated_at"`
	CreatedBy    *uuid.UUID `db:"created_by" json:"created_by"`
	UpdatedBy    *uuid.UUID `db:"updated_by" json:"updated_by"`
}

type PmPowerTestPoint struct {
	ID                uuid.UUID        `db:"id" json:"id"`
	PmPowerTestID     uuid.UUID        `db:"pm_power_test_id" json:"pm_power_test_id"`
	EquipmentRole     string           `db:"equipment_role" json:"equipment_role"`
	Brand             *string          `db:"brand" json:"brand"`
	Model             *string          `db:"model" json:"model"`
	InputAcceptRange  *string          `db:"input_accept_range" json:"input_accept_range"`
	InputResultValue  *decimal.Decimal `db:"input_result_value" json:"input_result_value"`
	InputUnit         *string          `db:"input_unit" json:"input_unit"`
	OutputAcceptRange *string          `db:"output_accept_range" json:"output_accept_range"`
	OutputResultValue *decimal.Decimal `db:"output_result_value" json:"output_result_value"`
	OutputUnit        *string          `db:"output_unit" json:"output_unit"`
	Result            *string          `db:"result" json:"result"`
	CorrectiveAction  *string          `db:"corrective_action" json:"corrective_action"`
	CreatedAt         time.Time        `db:"created_at" json:"created_at"`
	UpdatedAt         time.Time        `db:"updated_at" json:"updated_at"`
	CreatedBy         *uuid.UUID       `db:"created_by" json:"created_by"`
	UpdatedBy         *uuid.UUID       `db:"updated_by" json:"updated_by"`
}

type PmReport struct {
	ID               uuid.UUID  `db:"id" json:"id"`
	WorkOrderID      uuid.UUID  `db:"work_order_id" json:"work_order_id"`
	WorkOrderRoundID uuid.UUID  `db:"work_order_round_id" json:"work_order_round_id"`
	PanelID          uuid.UUID  `db:"panel_id" json:"panel_id"`
	EngineerID       *uuid.UUID `db:"engineer_id" json:"engineer_id"`
	SubmittedBy      *uuid.UUID `db:"submitted_by" json:"submitted_by"`
	Status           string     `db:"status" json:"status"`
	Note             *string    `db:"note" json:"note"`
	ReportDate       *time.Time `db:"report_date" json:"report_date"`
	SubmittedAt      *time.Time `db:"submitted_at" json:"submitted_at"`
	CreatedAt        time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt        time.Time  `db:"updated_at" json:"updated_at"`
	CreatedBy        *uuid.UUID `db:"created_by" json:"created_by"`
	UpdatedBy        *uuid.UUID `db:"updated_by" json:"updated_by"`
}

type RtuProblemTopic struct {
	ID        uuid.UUID  `db:"id" json:"id"`
	Code      string     `db:"code" json:"code"`
	Name      string     `db:"name" json:"name"`
	SortOrder int16      `db:"sort_order" json:"sort_order"`
	Active    bool       `db:"active" json:"active"`
	CreatedAt time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt time.Time  `db:"updated_at" json:"updated_at"`
	CreatedBy *uuid.UUID `db:"created_by" json:"created_by"`
	UpdatedBy *uuid.UUID `db:"updated_by" json:"updated_by"`
}

type WoApproval struct {
	ID               uuid.UUID   `db:"id" json:"id"`
	WorkOrderID      uuid.UUID   `db:"work_order_id" json:"work_order_id"`
	WorkOrderRoundID uuid.UUID   `db:"work_order_round_id" json:"work_order_round_id"`
	ReviewerID       uuid.UUID   `db:"reviewer_id" json:"reviewer_id"`
	Decision         string      `db:"decision" json:"decision"`
	RepairDate       *httpx.Date `db:"repair_date" json:"repair_date"`
	NewWorkOrderID   *uuid.UUID  `db:"new_work_order_id" json:"new_work_order_id"`
	Note             *string     `db:"note" json:"note"`
	ReviewedAt       time.Time   `db:"reviewed_at" json:"reviewed_at"`
	CreatedAt        time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt        time.Time   `db:"updated_at" json:"updated_at"`
	CreatedBy        *uuid.UUID  `db:"created_by" json:"created_by"`
	UpdatedBy        *uuid.UUID  `db:"updated_by" json:"updated_by"`
}

type WorkOrder struct {
	ID                 uuid.UUID   `db:"id" json:"id"`
	WorkOrderNo        string      `db:"work_order_no" json:"work_order_no"`
	WorkOrderType      string      `db:"work_order_type" json:"work_order_type"`
	PmScheduleType     *string     `db:"pm_schedule_type" json:"pm_schedule_type"`
	PanelID            uuid.UUID   `db:"panel_id" json:"panel_id"`
	PanelDeviceID      *uuid.UUID  `db:"panel_device_id" json:"panel_device_id"`
	Title              *string     `db:"title" json:"title"`
	Description        *string     `db:"description" json:"description"`
	Status             string      `db:"status" json:"status"`
	Priority           string      `db:"priority" json:"priority"`
	Source             string      `db:"source" json:"source"`
	RequestedBy        uuid.UUID   `db:"requested_by" json:"requested_by"`
	CurrentRoundID     *uuid.UUID  `db:"current_round_id" json:"current_round_id"`
	RelatedWorkOrderID *uuid.UUID  `db:"related_work_order_id" json:"related_work_order_id"`
	PlannedDate        *httpx.Date `db:"planned_date" json:"planned_date"`
	DueDate            *httpx.Date `db:"due_date" json:"due_date"`
	ClosedAt           *time.Time  `db:"closed_at" json:"closed_at"`
	Active             bool        `db:"active" json:"active"`
	CreatedAt          time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt          time.Time   `db:"updated_at" json:"updated_at"`
	CreatedBy          *uuid.UUID  `db:"created_by" json:"created_by"`
	UpdatedBy          *uuid.UUID  `db:"updated_by" json:"updated_by"`
}

type WorkOrderActivityLog struct {
	ID               uuid.UUID  `db:"id" json:"id"`
	WorkOrderID      uuid.UUID  `db:"work_order_id" json:"work_order_id"`
	WorkOrderRoundID *uuid.UUID `db:"work_order_round_id" json:"work_order_round_id"`
	Action           string     `db:"action" json:"action"`
	FromStatus       *string    `db:"from_status" json:"from_status"`
	ToStatus         *string    `db:"to_status" json:"to_status"`
	FromAssignee     *uuid.UUID `db:"from_assignee" json:"from_assignee"`
	ToAssignee       *uuid.UUID `db:"to_assignee" json:"to_assignee"`
	Note             *string    `db:"note" json:"note"`
	ActorID          uuid.UUID  `db:"actor_id" json:"actor_id"`
	CreatedAt        time.Time  `db:"created_at" json:"created_at"`
}

type WorkOrderRound struct {
	ID          uuid.UUID        `db:"id" json:"id"`
	WorkOrderID uuid.UUID        `db:"work_order_id" json:"work_order_id"`
	RoundNo     int16            `db:"round_no" json:"round_no"`
	AssignedTo  uuid.UUID        `db:"assigned_to" json:"assigned_to"`
	AssignedBy  uuid.UUID        `db:"assigned_by" json:"assigned_by"`
	AssignedAt  time.Time        `db:"assigned_at" json:"assigned_at"`
	CheckInAt   *time.Time       `db:"check_in_at" json:"check_in_at"`
	CheckInLat  *decimal.Decimal `db:"check_in_lat" json:"check_in_lat"`
	CheckInLng  *decimal.Decimal `db:"check_in_lng" json:"check_in_lng"`
	CheckOutAt  *time.Time       `db:"check_out_at" json:"check_out_at"`
	CheckOutLat *decimal.Decimal `db:"check_out_lat" json:"check_out_lat"`
	CheckOutLng *decimal.Decimal `db:"check_out_lng" json:"check_out_lng"`
	SubmittedAt *time.Time       `db:"submitted_at" json:"submitted_at"`
	Active      bool             `db:"active" json:"active"`
	CreatedAt   time.Time        `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time        `db:"updated_at" json:"updated_at"`
	CreatedBy   *uuid.UUID       `db:"created_by" json:"created_by"`
	UpdatedBy   *uuid.UUID       `db:"updated_by" json:"updated_by"`
}
