// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*)::bigint FROM rtu.notifications
WHERE recipient_id = $1::uuid AND is_read = false
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, recipientID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, recipientID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO rtu.notifications (
    work_order_id, recipient_id, type, title, message, created_by, updated_by
)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::varchar,
    $4::varchar,
    $5::text,
    $6::uuid,
    $7::uuid
)
RETURNING id, work_order_id, recipient_id, type, title, message, is_read, read_at, created_at, updated_at, created_by, updated_by
`

type CreateNotificationParams struct {
	WorkOrderID uuid.UUID  `db:"work_order_id" json:"work_order_id"`
	RecipientID uuid.UUID  `db:"recipient_id" json:"recipient_id"`
	Type        string     `db:"type" json:"type"`
	Title       *string    `db:"title" json:"title"`
	Message     *string    `db:"message" json:"message"`
	CreatedBy   *uuid.UUID `db:"created_by" json:"created_by"`
	UpdatedBy   *uuid.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.WorkOrderID,
		arg.RecipientID,
		arg.Type,
		arg.Title,
		arg.Message,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.RecipientID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.IsRead,
		&i.ReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteNotification = `-- name: DeleteNotification :execrows
DELETE FROM rtu.notifications WHERE id = $1::uuid AND recipient_id = $2::uuid
`

type DeleteNotificationParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	RecipientID uuid.UUID `db:"recipient_id" json:"recipient_id"`
}

func (q *Queries) DeleteNotification(ctx context.Context, arg DeleteNotificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotification, arg.ID, arg.RecipientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNotification = `-- name: GetNotification :one
SELECT id, work_order_id, recipient_id, type, title, message, is_read, read_at, created_at, updated_at, created_by, updated_by FROM rtu.notifications WHERE id = $1::uuid
`

func (q *Queries) GetNotification(ctx context.Context, id uuid.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotification, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.RecipientID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.IsRead,
		&i.ReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :execrows
UPDATE rtu.notifications SET
    is_read    = true,
    read_at    = now(),
    updated_by = $1::uuid
WHERE recipient_id = $2::uuid AND is_read = false
`

type MarkAllNotificationsReadParams struct {
	UpdatedBy   *uuid.UUID `db:"updated_by" json:"updated_by"`
	RecipientID uuid.UUID  `db:"recipient_id" json:"recipient_id"`
}

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, arg MarkAllNotificationsReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAllNotificationsRead, arg.UpdatedBy, arg.RecipientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE rtu.notifications SET
    is_read    = true,
    read_at    = now(),
    updated_by = $1::uuid
WHERE id = $2::uuid AND recipient_id = $3::uuid
RETURNING id, work_order_id, recipient_id, type, title, message, is_read, read_at, created_at, updated_at, created_by, updated_by
`

type MarkNotificationReadParams struct {
	UpdatedBy   *uuid.UUID `db:"updated_by" json:"updated_by"`
	ID          uuid.UUID  `db:"id" json:"id"`
	RecipientID uuid.UUID  `db:"recipient_id" json:"recipient_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, arg.UpdatedBy, arg.ID, arg.RecipientID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.RecipientID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.IsRead,
		&i.ReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
