// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: panels.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/rtu-api/internal/httpx"
	"github.com/shopspring/decimal"
)

const createPanel = `-- name: CreatePanel :one
INSERT INTO rtu.panels (code, location, latitude, longitude, install_date, active, created_by, updated_by)
VALUES (
    $1::varchar,
    $2::text,
    $3::numeric,
    $4::numeric,
    $5::date,
    COALESCE($6::boolean, true),
    $7::uuid,
    $8::uuid
)
RETURNING id, code, location, latitude, longitude, active, created_at, updated_at, created_by, updated_by, install_date, last_pm_date, next_pm_date
`

type CreatePanelParams struct {
	Code        string           `db:"code" json:"code"`
	Location    *string          `db:"location" json:"location"`
	Latitude    *decimal.Decimal `db:"latitude" json:"latitude"`
	Longitude   *decimal.Decimal `db:"longitude" json:"longitude"`
	InstallDate *httpx.Date      `db:"install_date" json:"install_date"`
	Active      *bool            `db:"active" json:"active"`
	CreatedBy   *uuid.UUID       `db:"created_by" json:"created_by"`
	UpdatedBy   *uuid.UUID       `db:"updated_by" json:"updated_by"`
}

func (q *Queries) CreatePanel(ctx context.Context, arg CreatePanelParams) (Panel, error) {
	row := q.db.QueryRow(ctx, createPanel,
		arg.Code,
		arg.Location,
		arg.Latitude,
		arg.Longitude,
		arg.InstallDate,
		arg.Active,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Panel
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Location,
		&i.Latitude,
		&i.Longitude,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.InstallDate,
		&i.LastPmDate,
		&i.NextPmDate,
	)
	return i, err
}

const deletePanel = `-- name: DeletePanel :execrows
DELETE FROM rtu.panels WHERE id = $1::uuid
`

func (q *Queries) DeletePanel(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePanel, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPanel = `-- name: GetPanel :one
SELECT id, code, location, latitude, longitude, active, created_at, updated_at, created_by, updated_by, install_date, last_pm_date, next_pm_date FROM rtu.panels WHERE id = $1::uuid
`

func (q *Queries) GetPanel(ctx context.Context, id uuid.UUID) (Panel, error) {
	row := q.db.QueryRow(ctx, getPanel, id)
	var i Panel
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Location,
		&i.Latitude,
		&i.Longitude,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.InstallDate,
		&i.LastPmDate,
		&i.NextPmDate,
	)
	return i, err
}

const getPanelByCode = `-- name: GetPanelByCode :one
SELECT id, code, location, latitude, longitude, active, created_at, updated_at, created_by, updated_by, install_date, last_pm_date, next_pm_date FROM rtu.panels WHERE code = $1::varchar
`

func (q *Queries) GetPanelByCode(ctx context.Context, code string) (Panel, error) {
	row := q.db.QueryRow(ctx, getPanelByCode, code)
	var i Panel
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Location,
		&i.Latitude,
		&i.Longitude,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.InstallDate,
		&i.LastPmDate,
		&i.NextPmDate,
	)
	return i, err
}

const panelExists = `-- name: PanelExists :one
SELECT EXISTS (SELECT 1 FROM rtu.panels WHERE id = $1::uuid) AS found
`

func (q *Queries) PanelExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, panelExists, id)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const panelIsActive = `-- name: PanelIsActive :one
SELECT active FROM rtu.panels WHERE id = $1::uuid
`

func (q *Queries) PanelIsActive(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, panelIsActive, id)
	var active bool
	err := row.Scan(&active)
	return active, err
}

const setPanelActive = `-- name: SetPanelActive :one
UPDATE rtu.panels SET
    active     = $1::boolean,
    updated_by = $2::uuid
WHERE id = $3::uuid
RETURNING id, code, location, latitude, longitude, active, created_at, updated_at, created_by, updated_by, install_date, last_pm_date, next_pm_date
`

type SetPanelActiveParams struct {
	Active    bool       `db:"active" json:"active"`
	UpdatedBy *uuid.UUID `db:"updated_by" json:"updated_by"`
	ID        uuid.UUID  `db:"id" json:"id"`
}

func (q *Queries) SetPanelActive(ctx context.Context, arg SetPanelActiveParams) (Panel, error) {
	row := q.db.QueryRow(ctx, setPanelActive, arg.Active, arg.UpdatedBy, arg.ID)
	var i Panel
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Location,
		&i.Latitude,
		&i.Longitude,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.InstallDate,
		&i.LastPmDate,
		&i.NextPmDate,
	)
	return i, err
}

const updatePanel = `-- name: UpdatePanel :one
UPDATE rtu.panels SET
    code         = CASE WHEN $1::boolean THEN $2::varchar ELSE code END,
    location     = CASE WHEN $3::boolean THEN $4::text ELSE location END,
    latitude     = CASE WHEN $5::boolean THEN $6::numeric ELSE latitude END,
    longitude    = CASE WHEN $7::boolean THEN $8::numeric ELSE longitude END,
    install_date = CASE WHEN $9::boolean THEN $10::date ELSE install_date END,
    active       = CASE WHEN $11::boolean THEN $12::boolean ELSE active END,
    updated_by   = $13::uuid
WHERE id = $14::uuid
RETURNING id, code, location, latitude, longitude, active, created_at, updated_at, created_by, updated_by, install_date, last_pm_date, next_pm_date
`

type UpdatePanelParams struct {
	CodeDoUpdate        bool             `db:"code_do_update" json:"code_do_update"`
	Code                string           `db:"code" json:"code"`
	LocationDoUpdate    bool             `db:"location_do_update" json:"location_do_update"`
	Location            *string          `db:"location" json:"location"`
	LatitudeDoUpdate    bool             `db:"latitude_do_update" json:"latitude_do_update"`
	Latitude            *decimal.Decimal `db:"latitude" json:"latitude"`
	LongitudeDoUpdate   bool             `db:"longitude_do_update" json:"longitude_do_update"`
	Longitude           *decimal.Decimal `db:"longitude" json:"longitude"`
	InstallDateDoUpdate bool             `db:"install_date_do_update" json:"install_date_do_update"`
	InstallDate         *httpx.Date      `db:"install_date" json:"install_date"`
	ActiveDoUpdate      bool             `db:"active_do_update" json:"active_do_update"`
	Active              bool             `db:"active" json:"active"`
	UpdatedBy           *uuid.UUID       `db:"updated_by" json:"updated_by"`
	ID                  uuid.UUID        `db:"id" json:"id"`
}

func (q *Queries) UpdatePanel(ctx context.Context, arg UpdatePanelParams) (Panel, error) {
	row := q.db.QueryRow(ctx, updatePanel,
		arg.CodeDoUpdate,
		arg.Code,
		arg.LocationDoUpdate,
		arg.Location,
		arg.LatitudeDoUpdate,
		arg.Latitude,
		arg.LongitudeDoUpdate,
		arg.Longitude,
		arg.InstallDateDoUpdate,
		arg.InstallDate,
		arg.ActiveDoUpdate,
		arg.Active,
		arg.UpdatedBy,
		arg.ID,
	)
	var i Panel
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Location,
		&i.Latitude,
		&i.Longitude,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.InstallDate,
		&i.LastPmDate,
		&i.NextPmDate,
	)
	return i, err
}

const updatePanelPmDates = `-- name: UpdatePanelPmDates :one
UPDATE rtu.panels SET
    last_pm_date = $1::date,
    next_pm_date = $2::date,
    updated_by   = $3::uuid
WHERE id = $4::uuid
RETURNING id, code, location, latitude, longitude, active, created_at, updated_at, created_by, updated_by, install_date, last_pm_date, next_pm_date
`

type UpdatePanelPmDatesParams struct {
	LastPmDate httpx.Date `db:"last_pm_date" json:"last_pm_date"`
	NextPmDate httpx.Date `db:"next_pm_date" json:"next_pm_date"`
	UpdatedBy  *uuid.UUID `db:"updated_by" json:"updated_by"`
	ID         uuid.UUID  `db:"id" json:"id"`
}

func (q *Queries) UpdatePanelPmDates(ctx context.Context, arg UpdatePanelPmDatesParams) (Panel, error) {
	row := q.db.QueryRow(ctx, updatePanelPmDates,
		arg.LastPmDate,
		arg.NextPmDate,
		arg.UpdatedBy,
		arg.ID,
	)
	var i Panel
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Location,
		&i.Latitude,
		&i.Longitude,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.InstallDate,
		&i.LastPmDate,
		&i.NextPmDate,
	)
	return i, err
}
