// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: panel_devices.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/rtu-api/internal/httpx"
)

const createPanelDevice = `-- name: CreatePanelDevice :one
INSERT INTO rtu.panel_devices (
    panel_id, device_model_id, tag_name, serial_number, asset_code,
    firmware_version, communication_status, health_status,
    installed_at, last_seen_at, note, active, created_by, updated_by
)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::varchar,
    $4::varchar,
    $5::varchar,
    $6::varchar,
    COALESCE($7::varchar, 'UNKNOWN'),
    COALESCE($8::varchar, 'UNKNOWN'),
    $9::date,
    $10::timestamptz,
    $11::text,
    COALESCE($12::boolean, true),
    $13::uuid,
    $14::uuid
)
RETURNING id, panel_id, device_model_id, tag_name, serial_number, asset_code, firmware_version, communication_status, health_status, installed_at, last_seen_at, note, active, created_at, updated_at, created_by, updated_by
`

type CreatePanelDeviceParams struct {
	PanelID             uuid.UUID   `db:"panel_id" json:"panel_id"`
	DeviceModelID       uuid.UUID   `db:"device_model_id" json:"device_model_id"`
	TagName             *string     `db:"tag_name" json:"tag_name"`
	SerialNumber        *string     `db:"serial_number" json:"serial_number"`
	AssetCode           *string     `db:"asset_code" json:"asset_code"`
	FirmwareVersion     *string     `db:"firmware_version" json:"firmware_version"`
	CommunicationStatus *string     `db:"communication_status" json:"communication_status"`
	HealthStatus        *string     `db:"health_status" json:"health_status"`
	InstalledAt         *httpx.Date `db:"installed_at" json:"installed_at"`
	LastSeenAt          *time.Time  `db:"last_seen_at" json:"last_seen_at"`
	Note                *string     `db:"note" json:"note"`
	Active              *bool       `db:"active" json:"active"`
	CreatedBy           *uuid.UUID  `db:"created_by" json:"created_by"`
	UpdatedBy           *uuid.UUID  `db:"updated_by" json:"updated_by"`
}

func (q *Queries) CreatePanelDevice(ctx context.Context, arg CreatePanelDeviceParams) (PanelDevice, error) {
	row := q.db.QueryRow(ctx, createPanelDevice,
		arg.PanelID,
		arg.DeviceModelID,
		arg.TagName,
		arg.SerialNumber,
		arg.AssetCode,
		arg.FirmwareVersion,
		arg.CommunicationStatus,
		arg.HealthStatus,
		arg.InstalledAt,
		arg.LastSeenAt,
		arg.Note,
		arg.Active,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i PanelDevice
	err := row.Scan(
		&i.ID,
		&i.PanelID,
		&i.DeviceModelID,
		&i.TagName,
		&i.SerialNumber,
		&i.AssetCode,
		&i.FirmwareVersion,
		&i.CommunicationStatus,
		&i.HealthStatus,
		&i.InstalledAt,
		&i.LastSeenAt,
		&i.Note,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deletePanelDevice = `-- name: DeletePanelDevice :execrows
DELETE FROM rtu.panel_devices WHERE id = $1::uuid
`

func (q *Queries) DeletePanelDevice(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePanelDevice, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPanelDevice = `-- name: GetPanelDevice :one
SELECT id, panel_id, device_model_id, tag_name, serial_number, asset_code, firmware_version, communication_status, health_status, installed_at, last_seen_at, note, active, created_at, updated_at, created_by, updated_by FROM rtu.panel_devices WHERE id = $1::uuid
`

func (q *Queries) GetPanelDevice(ctx context.Context, id uuid.UUID) (PanelDevice, error) {
	row := q.db.QueryRow(ctx, getPanelDevice, id)
	var i PanelDevice
	err := row.Scan(
		&i.ID,
		&i.PanelID,
		&i.DeviceModelID,
		&i.TagName,
		&i.SerialNumber,
		&i.AssetCode,
		&i.FirmwareVersion,
		&i.CommunicationStatus,
		&i.HealthStatus,
		&i.InstalledAt,
		&i.LastSeenAt,
		&i.Note,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const panelDeviceExists = `-- name: PanelDeviceExists :one
SELECT EXISTS (SELECT 1 FROM rtu.panel_devices WHERE id = $1::uuid) AS found
`

func (q *Queries) PanelDeviceExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, panelDeviceExists, id)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const panelDeviceIsActive = `-- name: PanelDeviceIsActive :one
SELECT active FROM rtu.panel_devices WHERE id = $1::uuid
`

func (q *Queries) PanelDeviceIsActive(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, panelDeviceIsActive, id)
	var active bool
	err := row.Scan(&active)
	return active, err
}

const setPanelDeviceActive = `-- name: SetPanelDeviceActive :one
UPDATE rtu.panel_devices SET
    active     = $1::boolean,
    updated_by = $2::uuid
WHERE id = $3::uuid
RETURNING id, panel_id, device_model_id, tag_name, serial_number, asset_code, firmware_version, communication_status, health_status, installed_at, last_seen_at, note, active, created_at, updated_at, created_by, updated_by
`

type SetPanelDeviceActiveParams struct {
	Active    bool       `db:"active" json:"active"`
	UpdatedBy *uuid.UUID `db:"updated_by" json:"updated_by"`
	ID        uuid.UUID  `db:"id" json:"id"`
}

func (q *Queries) SetPanelDeviceActive(ctx context.Context, arg SetPanelDeviceActiveParams) (PanelDevice, error) {
	row := q.db.QueryRow(ctx, setPanelDeviceActive, arg.Active, arg.UpdatedBy, arg.ID)
	var i PanelDevice
	err := row.Scan(
		&i.ID,
		&i.PanelID,
		&i.DeviceModelID,
		&i.TagName,
		&i.SerialNumber,
		&i.AssetCode,
		&i.FirmwareVersion,
		&i.CommunicationStatus,
		&i.HealthStatus,
		&i.InstalledAt,
		&i.LastSeenAt,
		&i.Note,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const updatePanelDevice = `-- name: UpdatePanelDevice :one
UPDATE rtu.panel_devices SET
    panel_id             = CASE WHEN $1::boolean THEN $2::uuid ELSE panel_id END,
    device_model_id      = CASE WHEN $3::boolean THEN $4::uuid ELSE device_model_id END,
    tag_name             = CASE WHEN $5::boolean THEN $6::varchar ELSE tag_name END,
    serial_number        = CASE WHEN $7::boolean THEN $8::varchar ELSE serial_number END,
    asset_code           = CASE WHEN $9::boolean THEN $10::varchar ELSE asset_code END,
    firmware_version     = CASE WHEN $11::boolean THEN $12::varchar ELSE firmware_version END,
    communication_status = CASE WHEN $13::boolean THEN $14::varchar ELSE communication_status END,
    health_status        = CASE WHEN $15::boolean THEN $16::varchar ELSE health_status END,
    installed_at         = CASE WHEN $17::boolean THEN $18::date ELSE installed_at END,
    last_seen_at         = CASE WHEN $19::boolean THEN $20::timestamptz ELSE last_seen_at END,
    note                 = CASE WHEN $21::boolean THEN $22::text ELSE note END,
    active               = CASE WHEN $23::boolean THEN $24::boolean ELSE active END,
    updated_by           = $25::uuid
WHERE id = $26::uuid
RETURNING id, panel_id, device_model_id, tag_name, serial_number, asset_code, firmware_version, communication_status, health_status, installed_at, last_seen_at, note, active, created_at, updated_at, created_by, updated_by
`

type UpdatePanelDeviceParams struct {
	PanelIDDoUpdate             bool        `db:"panel_id_do_update" json:"panel_id_do_update"`
	PanelID                     uuid.UUID   `db:"panel_id" json:"panel_id"`
	DeviceModelIDDoUpdate       bool        `db:"device_model_id_do_update" json:"device_model_id_do_update"`
	DeviceModelID               uuid.UUID   `db:"device_model_id" json:"device_model_id"`
	TagNameDoUpdate             bool        `db:"tag_name_do_update" json:"tag_name_do_update"`
	TagName                     *string     `db:"tag_name" json:"tag_name"`
	SerialNumberDoUpdate        bool        `db:"serial_number_do_update" json:"serial_number_do_update"`
	SerialNumber                *string     `db:"serial_number" json:"serial_number"`
	AssetCodeDoUpdate           bool        `db:"asset_code_do_update" json:"asset_code_do_update"`
	AssetCode                   *string     `db:"asset_code" json:"asset_code"`
	FirmwareVersionDoUpdate     bool        `db:"firmware_version_do_update" json:"firmware_version_do_update"`
	FirmwareVersion             *string     `db:"firmware_version" json:"firmware_version"`
	CommunicationStatusDoUpdate bool        `db:"communication_status_do_update" json:"communication_status_do_update"`
	CommunicationStatus         string      `db:"communication_status" json:"communication_status"`
	HealthStatusDoUpdate        bool        `db:"health_status_do_update" json:"health_status_do_update"`
	HealthStatus                string      `db:"health_status" json:"health_status"`
	InstalledAtDoUpdate         bool        `db:"installed_at_do_update" json:"installed_at_do_update"`
	InstalledAt                 *httpx.Date `db:"installed_at" json:"installed_at"`
	LastSeenAtDoUpdate          bool        `db:"last_seen_at_do_update" json:"last_seen_at_do_update"`
	LastSeenAt                  *time.Time  `db:"last_seen_at" json:"last_seen_at"`
	NoteDoUpdate                bool        `db:"note_do_update" json:"note_do_update"`
	Note                        *string     `db:"note" json:"note"`
	ActiveDoUpdate              bool        `db:"active_do_update" json:"active_do_update"`
	Active                      bool        `db:"active" json:"active"`
	UpdatedBy                   *uuid.UUID  `db:"updated_by" json:"updated_by"`
	ID                          uuid.UUID   `db:"id" json:"id"`
}

func (q *Queries) UpdatePanelDevice(ctx context.Context, arg UpdatePanelDeviceParams) (PanelDevice, error) {
	row := q.db.QueryRow(ctx, updatePanelDevice,
		arg.PanelIDDoUpdate,
		arg.PanelID,
		arg.DeviceModelIDDoUpdate,
		arg.DeviceModelID,
		arg.TagNameDoUpdate,
		arg.TagName,
		arg.SerialNumberDoUpdate,
		arg.SerialNumber,
		arg.AssetCodeDoUpdate,
		arg.AssetCode,
		arg.FirmwareVersionDoUpdate,
		arg.FirmwareVersion,
		arg.CommunicationStatusDoUpdate,
		arg.CommunicationStatus,
		arg.HealthStatusDoUpdate,
		arg.HealthStatus,
		arg.InstalledAtDoUpdate,
		arg.InstalledAt,
		arg.LastSeenAtDoUpdate,
		arg.LastSeenAt,
		arg.NoteDoUpdate,
		arg.Note,
		arg.ActiveDoUpdate,
		arg.Active,
		arg.UpdatedBy,
		arg.ID,
	)
	var i PanelDevice
	err := row.Scan(
		&i.ID,
		&i.PanelID,
		&i.DeviceModelID,
		&i.TagName,
		&i.SerialNumber,
		&i.AssetCode,
		&i.FirmwareVersion,
		&i.CommunicationStatus,
		&i.HealthStatus,
		&i.InstalledAt,
		&i.LastSeenAt,
		&i.Note,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const updatePanelDeviceStatus = `-- name: UpdatePanelDeviceStatus :one
UPDATE rtu.panel_devices SET
    communication_status = CASE WHEN $1::boolean THEN $2::varchar ELSE communication_status END,
    health_status        = CASE WHEN $3::boolean THEN $4::varchar ELSE health_status END,
    last_seen_at         = COALESCE($5::timestamptz, now()),
    updated_by           = $6::uuid
WHERE id = $7::uuid
RETURNING id, panel_id, device_model_id, tag_name, serial_number, asset_code, firmware_version, communication_status, health_status, installed_at, last_seen_at, note, active, created_at, updated_at, created_by, updated_by
`

type UpdatePanelDeviceStatusParams struct {
	CommunicationStatusDoUpdate bool       `db:"communication_status_do_update" json:"communication_status_do_update"`
	CommunicationStatus         string     `db:"communication_status" json:"communication_status"`
	HealthStatusDoUpdate        bool       `db:"health_status_do_update" json:"health_status_do_update"`
	HealthStatus                string     `db:"health_status" json:"health_status"`
	LastSeenAt                  *time.Time `db:"last_seen_at" json:"last_seen_at"`
	UpdatedBy                   *uuid.UUID `db:"updated_by" json:"updated_by"`
	ID                          uuid.UUID  `db:"id" json:"id"`
}

func (q *Queries) UpdatePanelDeviceStatus(ctx context.Context, arg UpdatePanelDeviceStatusParams) (PanelDevice, error) {
	row := q.db.QueryRow(ctx, updatePanelDeviceStatus,
		arg.CommunicationStatusDoUpdate,
		arg.CommunicationStatus,
		arg.HealthStatusDoUpdate,
		arg.HealthStatus,
		arg.LastSeenAt,
		arg.UpdatedBy,
		arg.ID,
	)
	var i PanelDevice
	err := row.Scan(
		&i.ID,
		&i.PanelID,
		&i.DeviceModelID,
		&i.TagName,
		&i.SerialNumber,
		&i.AssetCode,
		&i.FirmwareVersion,
		&i.CommunicationStatus,
		&i.HealthStatus,
		&i.InstalledAt,
		&i.LastSeenAt,
		&i.Note,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
