// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: panel_images.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createPanelImage = `-- name: CreatePanelImage :one
INSERT INTO rtu.panel_images (
    panel_id, image_type, s3_bucket, s3_key,
    original_name, mime_type, file_size, caption, sort_order,
    created_by, updated_by
)
VALUES (
    $1::uuid,
    $2::varchar,
    $3::varchar,
    $4::varchar,
    $5::varchar,
    $6::varchar,
    $7::bigint,
    $8::text,
    COALESCE($9::smallint, 0),
    $10::uuid,
    $11::uuid
)
RETURNING
    id, panel_id, image_type, s3_bucket, s3_key, original_name, mime_type, file_size,
    caption, sort_order, active, created_at, updated_at, created_by, updated_by
`

type CreatePanelImageParams struct {
	PanelID      uuid.UUID  `db:"panel_id" json:"panel_id"`
	ImageType    string     `db:"image_type" json:"image_type"`
	S3Bucket     string     `db:"s3_bucket" json:"s3_bucket"`
	S3Key        string     `db:"s3_key" json:"s3_key"`
	OriginalName *string    `db:"original_name" json:"original_name"`
	MimeType     string     `db:"mime_type" json:"mime_type"`
	FileSize     int64      `db:"file_size" json:"file_size"`
	Caption      *string    `db:"caption" json:"caption"`
	SortOrder    *int16     `db:"sort_order" json:"sort_order"`
	CreatedBy    *uuid.UUID `db:"created_by" json:"created_by"`
	UpdatedBy    *uuid.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) CreatePanelImage(ctx context.Context, arg CreatePanelImageParams) (PanelImage, error) {
	row := q.db.QueryRow(ctx, createPanelImage,
		arg.PanelID,
		arg.ImageType,
		arg.S3Bucket,
		arg.S3Key,
		arg.OriginalName,
		arg.MimeType,
		arg.FileSize,
		arg.Caption,
		arg.SortOrder,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i PanelImage
	err := row.Scan(
		&i.ID,
		&i.PanelID,
		&i.ImageType,
		&i.S3Bucket,
		&i.S3Key,
		&i.OriginalName,
		&i.MimeType,
		&i.FileSize,
		&i.Caption,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deletePanelImage = `-- name: DeletePanelImage :execrows
DELETE FROM rtu.panel_images WHERE id = $1::uuid AND panel_id = $2::uuid
`

type DeletePanelImageParams struct {
	ID      uuid.UUID `db:"id" json:"id"`
	PanelID uuid.UUID `db:"panel_id" json:"panel_id"`
}

func (q *Queries) DeletePanelImage(ctx context.Context, arg DeletePanelImageParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePanelImage, arg.ID, arg.PanelID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPanelImage = `-- name: GetPanelImage :one
SELECT
    id, panel_id, image_type, s3_bucket, s3_key, original_name, mime_type, file_size,
    caption, sort_order, active, created_at, updated_at, created_by, updated_by
FROM rtu.panel_images WHERE id = $1::uuid
`

func (q *Queries) GetPanelImage(ctx context.Context, id uuid.UUID) (PanelImage, error) {
	row := q.db.QueryRow(ctx, getPanelImage, id)
	var i PanelImage
	err := row.Scan(
		&i.ID,
		&i.PanelID,
		&i.ImageType,
		&i.S3Bucket,
		&i.S3Key,
		&i.OriginalName,
		&i.MimeType,
		&i.FileSize,
		&i.Caption,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getPanelImageForPanel = `-- name: GetPanelImageForPanel :one
SELECT
    id, panel_id, image_type, s3_bucket, s3_key, original_name, mime_type, file_size,
    caption, sort_order, active, created_at, updated_at, created_by, updated_by
FROM rtu.panel_images
WHERE id = $1::uuid AND panel_id = $2::uuid
`

type GetPanelImageForPanelParams struct {
	ID      uuid.UUID `db:"id" json:"id"`
	PanelID uuid.UUID `db:"panel_id" json:"panel_id"`
}

func (q *Queries) GetPanelImageForPanel(ctx context.Context, arg GetPanelImageForPanelParams) (PanelImage, error) {
	row := q.db.QueryRow(ctx, getPanelImageForPanel, arg.ID, arg.PanelID)
	var i PanelImage
	err := row.Scan(
		&i.ID,
		&i.PanelID,
		&i.ImageType,
		&i.S3Bucket,
		&i.S3Key,
		&i.OriginalName,
		&i.MimeType,
		&i.FileSize,
		&i.Caption,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const replacePanelImageFile = `-- name: ReplacePanelImageFile :one
UPDATE rtu.panel_images SET
    s3_key        = $1::varchar,
    mime_type     = $2::varchar,
    file_size     = $3::bigint,
    original_name = $4::varchar,
    updated_by    = $5::uuid
WHERE id = $6::uuid AND panel_id = $7::uuid
RETURNING
    id, panel_id, image_type, s3_bucket, s3_key, original_name, mime_type, file_size,
    caption, sort_order, active, created_at, updated_at, created_by, updated_by
`

type ReplacePanelImageFileParams struct {
	S3Key        string     `db:"s3_key" json:"s3_key"`
	MimeType     string     `db:"mime_type" json:"mime_type"`
	FileSize     int64      `db:"file_size" json:"file_size"`
	OriginalName *string    `db:"original_name" json:"original_name"`
	UpdatedBy    *uuid.UUID `db:"updated_by" json:"updated_by"`
	ID           uuid.UUID  `db:"id" json:"id"`
	PanelID      uuid.UUID  `db:"panel_id" json:"panel_id"`
}

func (q *Queries) ReplacePanelImageFile(ctx context.Context, arg ReplacePanelImageFileParams) (PanelImage, error) {
	row := q.db.QueryRow(ctx, replacePanelImageFile,
		arg.S3Key,
		arg.MimeType,
		arg.FileSize,
		arg.OriginalName,
		arg.UpdatedBy,
		arg.ID,
		arg.PanelID,
	)
	var i PanelImage
	err := row.Scan(
		&i.ID,
		&i.PanelID,
		&i.ImageType,
		&i.S3Bucket,
		&i.S3Key,
		&i.OriginalName,
		&i.MimeType,
		&i.FileSize,
		&i.Caption,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const updatePanelImage = `-- name: UpdatePanelImage :one
UPDATE rtu.panel_images SET
    image_type = CASE WHEN $1::boolean THEN $2::varchar ELSE image_type END,
    caption    = CASE WHEN $3::boolean THEN $4::text ELSE caption END,
    sort_order = CASE WHEN $5::boolean THEN $6::smallint ELSE sort_order END,
    updated_by = $7::uuid
WHERE id = $8::uuid AND panel_id = $9::uuid
RETURNING
    id, panel_id, image_type, s3_bucket, s3_key, original_name, mime_type, file_size,
    caption, sort_order, active, created_at, updated_at, created_by, updated_by
`

type UpdatePanelImageParams struct {
	ImageTypeDoUpdate bool       `db:"image_type_do_update" json:"image_type_do_update"`
	ImageType         string     `db:"image_type" json:"image_type"`
	CaptionDoUpdate   bool       `db:"caption_do_update" json:"caption_do_update"`
	Caption           *string    `db:"caption" json:"caption"`
	SortOrderDoUpdate bool       `db:"sort_order_do_update" json:"sort_order_do_update"`
	SortOrder         int16      `db:"sort_order" json:"sort_order"`
	UpdatedBy         *uuid.UUID `db:"updated_by" json:"updated_by"`
	ID                uuid.UUID  `db:"id" json:"id"`
	PanelID           uuid.UUID  `db:"panel_id" json:"panel_id"`
}

func (q *Queries) UpdatePanelImage(ctx context.Context, arg UpdatePanelImageParams) (PanelImage, error) {
	row := q.db.QueryRow(ctx, updatePanelImage,
		arg.ImageTypeDoUpdate,
		arg.ImageType,
		arg.CaptionDoUpdate,
		arg.Caption,
		arg.SortOrderDoUpdate,
		arg.SortOrder,
		arg.UpdatedBy,
		arg.ID,
		arg.PanelID,
	)
	var i PanelImage
	err := row.Scan(
		&i.ID,
		&i.PanelID,
		&i.ImageType,
		&i.S3Bucket,
		&i.S3Key,
		&i.OriginalName,
		&i.MimeType,
		&i.FileSize,
		&i.Caption,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
