// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pm_ground_tests.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const deletePmGroundTestByReport = `-- name: DeletePmGroundTestByReport :execrows
DELETE FROM rtu.pm_ground_tests WHERE pm_report_id = $1::uuid
`

func (q *Queries) DeletePmGroundTestByReport(ctx context.Context, pmReportID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePmGroundTestByReport, pmReportID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPmGroundTestByReport = `-- name: GetPmGroundTestByReport :one
SELECT id, pm_report_id, resistance_lg, resistance_ng, voltage_lg, voltage_ng, result, note, measured_by, measured_at, created_at, updated_at, created_by, updated_by FROM rtu.pm_ground_tests WHERE pm_report_id = $1::uuid
`

func (q *Queries) GetPmGroundTestByReport(ctx context.Context, pmReportID uuid.UUID) (PmGroundTest, error) {
	row := q.db.QueryRow(ctx, getPmGroundTestByReport, pmReportID)
	var i PmGroundTest
	err := row.Scan(
		&i.ID,
		&i.PmReportID,
		&i.ResistanceLg,
		&i.ResistanceNg,
		&i.VoltageLg,
		&i.VoltageNg,
		&i.Result,
		&i.Note,
		&i.MeasuredBy,
		&i.MeasuredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const pmGroundTestExists = `-- name: PmGroundTestExists :one
SELECT EXISTS (SELECT 1 FROM rtu.pm_ground_tests WHERE id = $1::uuid) AS found
`

func (q *Queries) PmGroundTestExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, pmGroundTestExists, id)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const upsertPmGroundTest = `-- name: UpsertPmGroundTest :one
INSERT INTO rtu.pm_ground_tests (
    pm_report_id, resistance_lg, resistance_ng, voltage_lg, voltage_ng,
    result, note, measured_by, measured_at, created_by, updated_by
)
VALUES (
    $1::uuid,
    $2::numeric,
    $3::numeric,
    $4::numeric,
    $5::numeric,
    $6::varchar,
    $7::text,
    $8::uuid,
    $9::timestamptz,
    $10::uuid,
    $11::uuid
)
ON CONFLICT (pm_report_id) DO UPDATE SET
    resistance_lg = EXCLUDED.resistance_lg,
    resistance_ng = EXCLUDED.resistance_ng,
    voltage_lg    = EXCLUDED.voltage_lg,
    voltage_ng    = EXCLUDED.voltage_ng,
    result        = EXCLUDED.result,
    note          = EXCLUDED.note,
    measured_by   = EXCLUDED.measured_by,
    measured_at   = EXCLUDED.measured_at,
    updated_by    = EXCLUDED.updated_by
RETURNING id, pm_report_id, resistance_lg, resistance_ng, voltage_lg, voltage_ng, result, note, measured_by, measured_at, created_at, updated_at, created_by, updated_by
`

type UpsertPmGroundTestParams struct {
	PmReportID   uuid.UUID        `db:"pm_report_id" json:"pm_report_id"`
	ResistanceLg *decimal.Decimal `db:"resistance_lg" json:"resistance_lg"`
	ResistanceNg *decimal.Decimal `db:"resistance_ng" json:"resistance_ng"`
	VoltageLg    *decimal.Decimal `db:"voltage_lg" json:"voltage_lg"`
	VoltageNg    *decimal.Decimal `db:"voltage_ng" json:"voltage_ng"`
	Result       *string          `db:"result" json:"result"`
	Note         *string          `db:"note" json:"note"`
	MeasuredBy   *uuid.UUID       `db:"measured_by" json:"measured_by"`
	MeasuredAt   *time.Time       `db:"measured_at" json:"measured_at"`
	CreatedBy    *uuid.UUID       `db:"created_by" json:"created_by"`
	UpdatedBy    *uuid.UUID       `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpsertPmGroundTest(ctx context.Context, arg UpsertPmGroundTestParams) (PmGroundTest, error) {
	row := q.db.QueryRow(ctx, upsertPmGroundTest,
		arg.PmReportID,
		arg.ResistanceLg,
		arg.ResistanceNg,
		arg.VoltageLg,
		arg.VoltageNg,
		arg.Result,
		arg.Note,
		arg.MeasuredBy,
		arg.MeasuredAt,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i PmGroundTest
	err := row.Scan(
		&i.ID,
		&i.PmReportID,
		&i.ResistanceLg,
		&i.ResistanceNg,
		&i.VoltageLg,
		&i.VoltageNg,
		&i.Result,
		&i.Note,
		&i.MeasuredBy,
		&i.MeasuredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
