// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pm_power_tests.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deletePmPowerTestByReport = `-- name: DeletePmPowerTestByReport :execrows
DELETE FROM rtu.pm_power_tests WHERE pm_report_id = $1::uuid
`

func (q *Queries) DeletePmPowerTestByReport(ctx context.Context, pmReportID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePmPowerTestByReport, pmReportID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPmPowerTestByReport = `-- name: GetPmPowerTestByReport :one
SELECT id, pm_report_id, instrument_id, tested_by, tested_at, created_at, updated_at, created_by, updated_by FROM rtu.pm_power_tests WHERE pm_report_id = $1::uuid
`

func (q *Queries) GetPmPowerTestByReport(ctx context.Context, pmReportID uuid.UUID) (PmPowerTest, error) {
	row := q.db.QueryRow(ctx, getPmPowerTestByReport, pmReportID)
	var i PmPowerTest
	err := row.Scan(
		&i.ID,
		&i.PmReportID,
		&i.InstrumentID,
		&i.TestedBy,
		&i.TestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const upsertPmPowerTest = `-- name: UpsertPmPowerTest :one
INSERT INTO rtu.pm_power_tests (
    pm_report_id, instrument_id, tested_by, tested_at, created_by, updated_by
)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4::timestamptz,
    $5::uuid,
    $6::uuid
)
ON CONFLICT (pm_report_id) DO UPDATE SET
    instrument_id = EXCLUDED.instrument_id,
    tested_by     = EXCLUDED.tested_by,
    tested_at     = EXCLUDED.tested_at,
    updated_by    = EXCLUDED.updated_by
RETURNING id, pm_report_id, instrument_id, tested_by, tested_at, created_at, updated_at, created_by, updated_by
`

type UpsertPmPowerTestParams struct {
	PmReportID   uuid.UUID  `db:"pm_report_id" json:"pm_report_id"`
	InstrumentID *uuid.UUID `db:"instrument_id" json:"instrument_id"`
	TestedBy     *uuid.UUID `db:"tested_by" json:"tested_by"`
	TestedAt     *time.Time `db:"tested_at" json:"tested_at"`
	CreatedBy    *uuid.UUID `db:"created_by" json:"created_by"`
	UpdatedBy    *uuid.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpsertPmPowerTest(ctx context.Context, arg UpsertPmPowerTestParams) (PmPowerTest, error) {
	row := q.db.QueryRow(ctx, upsertPmPowerTest,
		arg.PmReportID,
		arg.InstrumentID,
		arg.TestedBy,
		arg.TestedAt,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i PmPowerTest
	err := row.Scan(
		&i.ID,
		&i.PmReportID,
		&i.InstrumentID,
		&i.TestedBy,
		&i.TestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
