// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pm_power_test_points.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type BulkCreatePmPowerTestPointsParams struct {
	PmPowerTestID     uuid.UUID        `db:"pm_power_test_id" json:"pm_power_test_id"`
	EquipmentRole     string           `db:"equipment_role" json:"equipment_role"`
	Brand             *string          `db:"brand" json:"brand"`
	Model             *string          `db:"model" json:"model"`
	InputAcceptRange  *string          `db:"input_accept_range" json:"input_accept_range"`
	InputResultValue  *decimal.Decimal `db:"input_result_value" json:"input_result_value"`
	InputUnit         *string          `db:"input_unit" json:"input_unit"`
	OutputAcceptRange *string          `db:"output_accept_range" json:"output_accept_range"`
	OutputResultValue *decimal.Decimal `db:"output_result_value" json:"output_result_value"`
	OutputUnit        *string          `db:"output_unit" json:"output_unit"`
	Result            *string          `db:"result" json:"result"`
	CorrectiveAction  *string          `db:"corrective_action" json:"corrective_action"`
	CreatedBy         *uuid.UUID       `db:"created_by" json:"created_by"`
}

const deletePmPowerTestPointsByTest = `-- name: DeletePmPowerTestPointsByTest :execrows
DELETE FROM rtu.pm_power_test_points WHERE pm_power_test_id = $1::uuid
`

func (q *Queries) DeletePmPowerTestPointsByTest(ctx context.Context, pmPowerTestID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePmPowerTestPointsByTest, pmPowerTestID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPmPowerTestPointsByTest = `-- name: ListPmPowerTestPointsByTest :many
SELECT id, pm_power_test_id, equipment_role, brand, model, input_accept_range, input_result_value, input_unit, output_accept_range, output_result_value, output_unit, result, corrective_action, created_at, updated_at, created_by, updated_by FROM rtu.pm_power_test_points
WHERE pm_power_test_id = $1::uuid
ORDER BY equipment_role
`

func (q *Queries) ListPmPowerTestPointsByTest(ctx context.Context, pmPowerTestID uuid.UUID) ([]PmPowerTestPoint, error) {
	rows, err := q.db.Query(ctx, listPmPowerTestPointsByTest, pmPowerTestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PmPowerTestPoint{}
	for rows.Next() {
		var i PmPowerTestPoint
		if err := rows.Scan(
			&i.ID,
			&i.PmPowerTestID,
			&i.EquipmentRole,
			&i.Brand,
			&i.Model,
			&i.InputAcceptRange,
			&i.InputResultValue,
			&i.InputUnit,
			&i.OutputAcceptRange,
			&i.OutputResultValue,
			&i.OutputUnit,
			&i.Result,
			&i.CorrectiveAction,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pmPowerTestPointExists = `-- name: PmPowerTestPointExists :one
SELECT EXISTS (SELECT 1 FROM rtu.pm_power_test_points WHERE id = $1::uuid) AS found
`

func (q *Queries) PmPowerTestPointExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, pmPowerTestPointExists, id)
	var found bool
	err := row.Scan(&found)
	return found, err
}
