// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pm_reports.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPmReport = `-- name: CreatePmReport :one
INSERT INTO rtu.pm_reports (
    work_order_id, work_order_round_id, panel_id, engineer_id,
    note, report_date, created_by, updated_by
)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4::uuid,
    $5::text,
    $6::timestamptz,
    $7::uuid,
    $8::uuid
)
RETURNING id, work_order_id, work_order_round_id, panel_id, engineer_id, submitted_by, status, note, report_date, submitted_at, created_at, updated_at, created_by, updated_by
`

type CreatePmReportParams struct {
	WorkOrderID      uuid.UUID  `db:"work_order_id" json:"work_order_id"`
	WorkOrderRoundID uuid.UUID  `db:"work_order_round_id" json:"work_order_round_id"`
	PanelID          uuid.UUID  `db:"panel_id" json:"panel_id"`
	EngineerID       *uuid.UUID `db:"engineer_id" json:"engineer_id"`
	Note             *string    `db:"note" json:"note"`
	ReportDate       *time.Time `db:"report_date" json:"report_date"`
	CreatedBy        *uuid.UUID `db:"created_by" json:"created_by"`
	UpdatedBy        *uuid.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) CreatePmReport(ctx context.Context, arg CreatePmReportParams) (PmReport, error) {
	row := q.db.QueryRow(ctx, createPmReport,
		arg.WorkOrderID,
		arg.WorkOrderRoundID,
		arg.PanelID,
		arg.EngineerID,
		arg.Note,
		arg.ReportDate,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i PmReport
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.WorkOrderRoundID,
		&i.PanelID,
		&i.EngineerID,
		&i.SubmittedBy,
		&i.Status,
		&i.Note,
		&i.ReportDate,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deletePmReport = `-- name: DeletePmReport :execrows
DELETE FROM rtu.pm_reports WHERE id = $1::uuid AND status = 'DRAFT'
`

func (q *Queries) DeletePmReport(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePmReport, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPmReport = `-- name: GetPmReport :one
SELECT id, work_order_id, work_order_round_id, panel_id, engineer_id, submitted_by, status, note, report_date, submitted_at, created_at, updated_at, created_by, updated_by FROM rtu.pm_reports WHERE id = $1::uuid
`

func (q *Queries) GetPmReport(ctx context.Context, id uuid.UUID) (PmReport, error) {
	row := q.db.QueryRow(ctx, getPmReport, id)
	var i PmReport
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.WorkOrderRoundID,
		&i.PanelID,
		&i.EngineerID,
		&i.SubmittedBy,
		&i.Status,
		&i.Note,
		&i.ReportDate,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getPmReportByRound = `-- name: GetPmReportByRound :one
SELECT id, work_order_id, work_order_round_id, panel_id, engineer_id, submitted_by, status, note, report_date, submitted_at, created_at, updated_at, created_by, updated_by FROM rtu.pm_reports WHERE work_order_round_id = $1::uuid
`

func (q *Queries) GetPmReportByRound(ctx context.Context, workOrderRoundID uuid.UUID) (PmReport, error) {
	row := q.db.QueryRow(ctx, getPmReportByRound, workOrderRoundID)
	var i PmReport
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.WorkOrderRoundID,
		&i.PanelID,
		&i.EngineerID,
		&i.SubmittedBy,
		&i.Status,
		&i.Note,
		&i.ReportDate,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const pmReportExists = `-- name: PmReportExists :one
SELECT EXISTS (SELECT 1 FROM rtu.pm_reports WHERE id = $1::uuid) AS found
`

func (q *Queries) PmReportExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, pmReportExists, id)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const setPmReportSubmitted = `-- name: SetPmReportSubmitted :one
UPDATE rtu.pm_reports SET
    status       = 'SUBMITTED',
    submitted_by = $1::uuid,
    submitted_at = $2::timestamptz,
    updated_by   = $3::uuid
WHERE id = $4::uuid AND status = 'DRAFT'
RETURNING id, work_order_id, work_order_round_id, panel_id, engineer_id, submitted_by, status, note, report_date, submitted_at, created_at, updated_at, created_by, updated_by
`

type SetPmReportSubmittedParams struct {
	SubmittedBy *uuid.UUID `db:"submitted_by" json:"submitted_by"`
	SubmittedAt time.Time  `db:"submitted_at" json:"submitted_at"`
	UpdatedBy   *uuid.UUID `db:"updated_by" json:"updated_by"`
	ID          uuid.UUID  `db:"id" json:"id"`
}

func (q *Queries) SetPmReportSubmitted(ctx context.Context, arg SetPmReportSubmittedParams) (PmReport, error) {
	row := q.db.QueryRow(ctx, setPmReportSubmitted,
		arg.SubmittedBy,
		arg.SubmittedAt,
		arg.UpdatedBy,
		arg.ID,
	)
	var i PmReport
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.WorkOrderRoundID,
		&i.PanelID,
		&i.EngineerID,
		&i.SubmittedBy,
		&i.Status,
		&i.Note,
		&i.ReportDate,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const updatePmReport = `-- name: UpdatePmReport :one
UPDATE rtu.pm_reports SET
    engineer_id  = CASE WHEN $1::boolean THEN $2::uuid ELSE engineer_id END,
    note         = CASE WHEN $3::boolean THEN $4::text ELSE note END,
    report_date  = CASE WHEN $5::boolean THEN $6::timestamptz ELSE report_date END,
    updated_by   = $7::uuid
WHERE id = $8::uuid AND status = 'DRAFT'
RETURNING id, work_order_id, work_order_round_id, panel_id, engineer_id, submitted_by, status, note, report_date, submitted_at, created_at, updated_at, created_by, updated_by
`

type UpdatePmReportParams struct {
	EngineerIDDoUpdate bool       `db:"engineer_id_do_update" json:"engineer_id_do_update"`
	EngineerID         *uuid.UUID `db:"engineer_id" json:"engineer_id"`
	NoteDoUpdate       bool       `db:"note_do_update" json:"note_do_update"`
	Note               *string    `db:"note" json:"note"`
	ReportDateDoUpdate bool       `db:"report_date_do_update" json:"report_date_do_update"`
	ReportDate         *time.Time `db:"report_date" json:"report_date"`
	UpdatedBy          *uuid.UUID `db:"updated_by" json:"updated_by"`
	ID                 uuid.UUID  `db:"id" json:"id"`
}

func (q *Queries) UpdatePmReport(ctx context.Context, arg UpdatePmReportParams) (PmReport, error) {
	row := q.db.QueryRow(ctx, updatePmReport,
		arg.EngineerIDDoUpdate,
		arg.EngineerID,
		arg.NoteDoUpdate,
		arg.Note,
		arg.ReportDateDoUpdate,
		arg.ReportDate,
		arg.UpdatedBy,
		arg.ID,
	)
	var i PmReport
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.WorkOrderRoundID,
		&i.PanelID,
		&i.EngineerID,
		&i.SubmittedBy,
		&i.Status,
		&i.Note,
		&i.ReportDate,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
