// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: problem_topics.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createProblemTopic = `-- name: CreateProblemTopic :one
INSERT INTO rtu.problem_topics (code, name, sort_order, active, created_by, updated_by)
VALUES (
    $1::varchar,
    $2::varchar,
    $3::smallint,
    COALESCE($4::boolean, true),
    $5::uuid,
    $6::uuid
)
RETURNING id, code, name, sort_order, active, created_at, updated_at, created_by, updated_by
`

type CreateProblemTopicParams struct {
	Code      string     `db:"code" json:"code"`
	Name      string     `db:"name" json:"name"`
	SortOrder int16      `db:"sort_order" json:"sort_order"`
	Active    *bool      `db:"active" json:"active"`
	CreatedBy *uuid.UUID `db:"created_by" json:"created_by"`
	UpdatedBy *uuid.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) CreateProblemTopic(ctx context.Context, arg CreateProblemTopicParams) (RtuProblemTopic, error) {
	row := q.db.QueryRow(ctx, createProblemTopic,
		arg.Code,
		arg.Name,
		arg.SortOrder,
		arg.Active,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i RtuProblemTopic
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteProblemTopic = `-- name: DeleteProblemTopic :execrows
DELETE FROM rtu.problem_topics WHERE id = $1::uuid
`

func (q *Queries) DeleteProblemTopic(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProblemTopic, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProblemTopic = `-- name: GetProblemTopic :one
SELECT id, code, name, sort_order, active, created_at, updated_at, created_by, updated_by FROM rtu.problem_topics WHERE id = $1::uuid
`

func (q *Queries) GetProblemTopic(ctx context.Context, id uuid.UUID) (RtuProblemTopic, error) {
	row := q.db.QueryRow(ctx, getProblemTopic, id)
	var i RtuProblemTopic
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getProblemTopicByCode = `-- name: GetProblemTopicByCode :one
SELECT id, code, name, sort_order, active, created_at, updated_at, created_by, updated_by FROM rtu.problem_topics WHERE code = $1::varchar
`

func (q *Queries) GetProblemTopicByCode(ctx context.Context, code string) (RtuProblemTopic, error) {
	row := q.db.QueryRow(ctx, getProblemTopicByCode, code)
	var i RtuProblemTopic
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getProblemTopicUsability = `-- name: GetProblemTopicUsability :one
SELECT active FROM rtu.problem_topics WHERE id = $1::uuid
`

func (q *Queries) GetProblemTopicUsability(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getProblemTopicUsability, id)
	var active bool
	err := row.Scan(&active)
	return active, err
}

const listProblemTopics = `-- name: ListProblemTopics :many
SELECT id, code, name, sort_order, active, created_at, updated_at, created_by, updated_by FROM rtu.problem_topics
WHERE ($1::boolean IS NULL OR active = $1::boolean)
ORDER BY sort_order ASC
`

func (q *Queries) ListProblemTopics(ctx context.Context, activeFilter *bool) ([]RtuProblemTopic, error) {
	rows, err := q.db.Query(ctx, listProblemTopics, activeFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RtuProblemTopic{}
	for rows.Next() {
		var i RtuProblemTopic
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.SortOrder,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const problemTopicExists = `-- name: ProblemTopicExists :one
SELECT EXISTS (SELECT 1 FROM rtu.problem_topics WHERE id = $1::uuid) AS found
`

func (q *Queries) ProblemTopicExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, problemTopicExists, id)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const setProblemTopicActive = `-- name: SetProblemTopicActive :one
UPDATE rtu.problem_topics SET
    active     = $1::boolean,
    updated_by = $2::uuid
WHERE id = $3::uuid
RETURNING id, code, name, sort_order, active, created_at, updated_at, created_by, updated_by
`

type SetProblemTopicActiveParams struct {
	Active    bool       `db:"active" json:"active"`
	UpdatedBy *uuid.UUID `db:"updated_by" json:"updated_by"`
	ID        uuid.UUID  `db:"id" json:"id"`
}

func (q *Queries) SetProblemTopicActive(ctx context.Context, arg SetProblemTopicActiveParams) (RtuProblemTopic, error) {
	row := q.db.QueryRow(ctx, setProblemTopicActive, arg.Active, arg.UpdatedBy, arg.ID)
	var i RtuProblemTopic
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const updateProblemTopic = `-- name: UpdateProblemTopic :one
UPDATE rtu.problem_topics SET
    code       = CASE WHEN $1::boolean THEN $2::varchar ELSE code END,
    name       = CASE WHEN $3::boolean THEN $4::varchar ELSE name END,
    sort_order = CASE WHEN $5::boolean THEN $6::smallint ELSE sort_order END,
    active     = CASE WHEN $7::boolean THEN $8::boolean ELSE active END,
    updated_by = $9::uuid
WHERE id = $10::uuid
RETURNING id, code, name, sort_order, active, created_at, updated_at, created_by, updated_by
`

type UpdateProblemTopicParams struct {
	CodeDoUpdate      bool       `db:"code_do_update" json:"code_do_update"`
	Code              string     `db:"code" json:"code"`
	NameDoUpdate      bool       `db:"name_do_update" json:"name_do_update"`
	Name              string     `db:"name" json:"name"`
	SortOrderDoUpdate bool       `db:"sort_order_do_update" json:"sort_order_do_update"`
	SortOrder         int16      `db:"sort_order" json:"sort_order"`
	ActiveDoUpdate    bool       `db:"active_do_update" json:"active_do_update"`
	Active            bool       `db:"active" json:"active"`
	UpdatedBy         *uuid.UUID `db:"updated_by" json:"updated_by"`
	ID                uuid.UUID  `db:"id" json:"id"`
}

func (q *Queries) UpdateProblemTopic(ctx context.Context, arg UpdateProblemTopicParams) (RtuProblemTopic, error) {
	row := q.db.QueryRow(ctx, updateProblemTopic,
		arg.CodeDoUpdate,
		arg.Code,
		arg.NameDoUpdate,
		arg.Name,
		arg.SortOrderDoUpdate,
		arg.SortOrder,
		arg.ActiveDoUpdate,
		arg.Active,
		arg.UpdatedBy,
		arg.ID,
	)
	var i RtuProblemTopic
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
