// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO rtu.refresh_tokens (
    user_id, token_hash, ip_address, user_agent, expires_at
)
VALUES (
    $1::uuid,
    $2::varchar,
    $3::varchar,
    $4::text,
    $5::timestamptz
)
RETURNING id, user_id, token_hash, ip_address, user_agent, revoked_at, expires_at, created_at, updated_at
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	TokenHash string    `db:"token_hash" json:"token_hash"`
	IpAddress *string   `db:"ip_address" json:"ip_address"`
	UserAgent *string   `db:"user_agent" json:"user_agent"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.IpAddress,
		&i.UserAgent,
		&i.RevokedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT
    rt.id, rt.user_id, rt.token_hash, rt.ip_address, rt.user_agent,
    rt.revoked_at, rt.expires_at, rt.created_at, rt.updated_at,
    u.active AS user_active
FROM rtu.refresh_tokens rt
INNER JOIN rtu.users u ON u.id = rt.user_id
WHERE rt.token_hash = $1::varchar
`

type GetRefreshTokenByHashRow struct {
	ID         uuid.UUID  `db:"id" json:"id"`
	UserID     uuid.UUID  `db:"user_id" json:"user_id"`
	TokenHash  string     `db:"token_hash" json:"token_hash"`
	IpAddress  *string    `db:"ip_address" json:"ip_address"`
	UserAgent  *string    `db:"user_agent" json:"user_agent"`
	RevokedAt  *time.Time `db:"revoked_at" json:"revoked_at"`
	ExpiresAt  time.Time  `db:"expires_at" json:"expires_at"`
	CreatedAt  time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt  time.Time  `db:"updated_at" json:"updated_at"`
	UserActive bool       `db:"user_active" json:"user_active"`
}

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (GetRefreshTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i GetRefreshTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.IpAddress,
		&i.UserAgent,
		&i.RevokedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserActive,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE rtu.refresh_tokens SET revoked_at = now()
WHERE id = $1::uuid AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}

const revokeRefreshTokensForUser = `-- name: RevokeRefreshTokensForUser :execrows
UPDATE rtu.refresh_tokens SET revoked_at = now()
WHERE user_id = $1::uuid AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshTokensForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshTokensForUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchRefreshTokenMeta = `-- name: TouchRefreshTokenMeta :exec
UPDATE rtu.refresh_tokens SET
    ip_address = $1::varchar,
    user_agent = $2::text
WHERE id = $3::uuid
`

type TouchRefreshTokenMetaParams struct {
	IpAddress *string   `db:"ip_address" json:"ip_address"`
	UserAgent *string   `db:"user_agent" json:"user_agent"`
	ID        uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) TouchRefreshTokenMeta(ctx context.Context, arg TouchRefreshTokenMetaParams) error {
	_, err := q.db.Exec(ctx, touchRefreshTokenMeta, arg.IpAddress, arg.UserAgent, arg.ID)
	return err
}
