// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*)::bigint FROM rtu.users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO rtu.users (
    employee_code, title, first_name, last_name, email, password_hash,
    position, active, created_by, updated_by
)
VALUES (
    $1::varchar,
    $2::varchar,
    $3::varchar,
    $4::varchar,
    $5::varchar,
    $6::text,
    $7::varchar,
    COALESCE($8::boolean, true),
    $9::uuid,
    $10::uuid
)
RETURNING id, employee_code, title, first_name, last_name, email, password_hash, position, active, last_login_at, created_at, updated_at, created_by, updated_by
`

type CreateUserParams struct {
	EmployeeCode string     `db:"employee_code" json:"employee_code"`
	Title        *string    `db:"title" json:"title"`
	FirstName    string     `db:"first_name" json:"first_name"`
	LastName     string     `db:"last_name" json:"last_name"`
	Email        string     `db:"email" json:"email"`
	PasswordHash string     `db:"password_hash" json:"password_hash"`
	Position     *string    `db:"position" json:"position"`
	Active       *bool      `db:"active" json:"active"`
	CreatedBy    *uuid.UUID `db:"created_by" json:"created_by"`
	UpdatedBy    *uuid.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.EmployeeCode,
		arg.Title,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PasswordHash,
		arg.Position,
		arg.Active,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeCode,
		&i.Title,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Position,
		&i.Active,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM rtu.users WHERE id = $1::uuid
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUser = `-- name: GetUser :one
SELECT id, employee_code, title, first_name, last_name, email, password_hash, position, active, last_login_at, created_at, updated_at, created_by, updated_by FROM rtu.users WHERE id = $1::uuid
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeCode,
		&i.Title,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Position,
		&i.Active,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT id, employee_code, title, first_name, last_name, email, password_hash, position, active, last_login_at, created_at, updated_at, created_by, updated_by FROM rtu.users
WHERE lower(email) = lower($1::varchar)
   OR employee_code = $1::varchar
LIMIT 1
`

func (q *Queries) GetUserByLogin(ctx context.Context, login string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, login)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeCode,
		&i.Title,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Position,
		&i.Active,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const setUserActive = `-- name: SetUserActive :one
UPDATE rtu.users SET
    active     = $1::boolean,
    updated_by = $2::uuid
WHERE id = $3::uuid
RETURNING id, employee_code, title, first_name, last_name, email, password_hash, position, active, last_login_at, created_at, updated_at, created_by, updated_by
`

type SetUserActiveParams struct {
	Active    bool       `db:"active" json:"active"`
	UpdatedBy *uuid.UUID `db:"updated_by" json:"updated_by"`
	ID        uuid.UUID  `db:"id" json:"id"`
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserActive, arg.Active, arg.UpdatedBy, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeCode,
		&i.Title,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Position,
		&i.Active,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const setUserPassword = `-- name: SetUserPassword :one
UPDATE rtu.users SET
    password_hash = $1::text,
    updated_by    = $2::uuid
WHERE id = $3::uuid
RETURNING id, employee_code, title, first_name, last_name, email, password_hash, position, active, last_login_at, created_at, updated_at, created_by, updated_by
`

type SetUserPasswordParams struct {
	PasswordHash string     `db:"password_hash" json:"password_hash"`
	UpdatedBy    *uuid.UUID `db:"updated_by" json:"updated_by"`
	ID           uuid.UUID  `db:"id" json:"id"`
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserPassword, arg.PasswordHash, arg.UpdatedBy, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeCode,
		&i.Title,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Position,
		&i.Active,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const touchUserLastLogin = `-- name: TouchUserLastLogin :exec
UPDATE rtu.users SET last_login_at = now() WHERE id = $1::uuid
`

func (q *Queries) TouchUserLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchUserLastLogin, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE rtu.users SET
    employee_code = CASE WHEN $1::boolean THEN $2::varchar ELSE employee_code END,
    title         = CASE WHEN $3::boolean THEN $4::varchar ELSE title END,
    first_name    = CASE WHEN $5::boolean THEN $6::varchar ELSE first_name END,
    last_name     = CASE WHEN $7::boolean THEN $8::varchar ELSE last_name END,
    email         = CASE WHEN $9::boolean THEN $10::varchar ELSE email END,
    password_hash = CASE WHEN $11::boolean THEN $12::text ELSE password_hash END,
    position      = CASE WHEN $13::boolean THEN $14::varchar ELSE position END,
    active        = CASE WHEN $15::boolean THEN $16::boolean ELSE active END,
    updated_by    = $17::uuid
WHERE id = $18::uuid
RETURNING id, employee_code, title, first_name, last_name, email, password_hash, position, active, last_login_at, created_at, updated_at, created_by, updated_by
`

type UpdateUserParams struct {
	EmployeeCodeDoUpdate bool       `db:"employee_code_do_update" json:"employee_code_do_update"`
	EmployeeCode         string     `db:"employee_code" json:"employee_code"`
	TitleDoUpdate        bool       `db:"title_do_update" json:"title_do_update"`
	Title                *string    `db:"title" json:"title"`
	FirstNameDoUpdate    bool       `db:"first_name_do_update" json:"first_name_do_update"`
	FirstName            string     `db:"first_name" json:"first_name"`
	LastNameDoUpdate     bool       `db:"last_name_do_update" json:"last_name_do_update"`
	LastName             string     `db:"last_name" json:"last_name"`
	EmailDoUpdate        bool       `db:"email_do_update" json:"email_do_update"`
	Email                string     `db:"email" json:"email"`
	PasswordHashDoUpdate bool       `db:"password_hash_do_update" json:"password_hash_do_update"`
	PasswordHash         string     `db:"password_hash" json:"password_hash"`
	PositionDoUpdate     bool       `db:"position_do_update" json:"position_do_update"`
	Position             *string    `db:"position" json:"position"`
	ActiveDoUpdate       bool       `db:"active_do_update" json:"active_do_update"`
	Active               bool       `db:"active" json:"active"`
	UpdatedBy            *uuid.UUID `db:"updated_by" json:"updated_by"`
	ID                   uuid.UUID  `db:"id" json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.EmployeeCodeDoUpdate,
		arg.EmployeeCode,
		arg.TitleDoUpdate,
		arg.Title,
		arg.FirstNameDoUpdate,
		arg.FirstName,
		arg.LastNameDoUpdate,
		arg.LastName,
		arg.EmailDoUpdate,
		arg.Email,
		arg.PasswordHashDoUpdate,
		arg.PasswordHash,
		arg.PositionDoUpdate,
		arg.Position,
		arg.ActiveDoUpdate,
		arg.Active,
		arg.UpdatedBy,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeCode,
		&i.Title,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Position,
		&i.Active,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
