// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wo_approvals.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/rtu-api/internal/httpx"
)

const createWoApproval = `-- name: CreateWoApproval :one
INSERT INTO rtu.wo_approvals (
    work_order_id, work_order_round_id, reviewer_id, decision, repair_date,
    new_work_order_id, note, reviewed_at, created_by, updated_by
)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4::varchar,
    $5::date,
    $6::uuid,
    $7::text,
    COALESCE($8::timestamptz, now()),
    $9::uuid,
    $10::uuid
)
RETURNING id, work_order_id, work_order_round_id, reviewer_id, decision, repair_date, new_work_order_id, note, reviewed_at, created_at, updated_at, created_by, updated_by
`

type CreateWoApprovalParams struct {
	WorkOrderID      uuid.UUID   `db:"work_order_id" json:"work_order_id"`
	WorkOrderRoundID uuid.UUID   `db:"work_order_round_id" json:"work_order_round_id"`
	ReviewerID       uuid.UUID   `db:"reviewer_id" json:"reviewer_id"`
	Decision         string      `db:"decision" json:"decision"`
	RepairDate       *httpx.Date `db:"repair_date" json:"repair_date"`
	NewWorkOrderID   *uuid.UUID  `db:"new_work_order_id" json:"new_work_order_id"`
	Note             *string     `db:"note" json:"note"`
	ReviewedAt       *time.Time  `db:"reviewed_at" json:"reviewed_at"`
	CreatedBy        *uuid.UUID  `db:"created_by" json:"created_by"`
	UpdatedBy        *uuid.UUID  `db:"updated_by" json:"updated_by"`
}

func (q *Queries) CreateWoApproval(ctx context.Context, arg CreateWoApprovalParams) (WoApproval, error) {
	row := q.db.QueryRow(ctx, createWoApproval,
		arg.WorkOrderID,
		arg.WorkOrderRoundID,
		arg.ReviewerID,
		arg.Decision,
		arg.RepairDate,
		arg.NewWorkOrderID,
		arg.Note,
		arg.ReviewedAt,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i WoApproval
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.WorkOrderRoundID,
		&i.ReviewerID,
		&i.Decision,
		&i.RepairDate,
		&i.NewWorkOrderID,
		&i.Note,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getWoApproval = `-- name: GetWoApproval :one
SELECT id, work_order_id, work_order_round_id, reviewer_id, decision, repair_date, new_work_order_id, note, reviewed_at, created_at, updated_at, created_by, updated_by FROM rtu.wo_approvals WHERE id = $1::uuid
`

func (q *Queries) GetWoApproval(ctx context.Context, id uuid.UUID) (WoApproval, error) {
	row := q.db.QueryRow(ctx, getWoApproval, id)
	var i WoApproval
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.WorkOrderRoundID,
		&i.ReviewerID,
		&i.Decision,
		&i.RepairDate,
		&i.NewWorkOrderID,
		&i.Note,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getWoApprovalByRound = `-- name: GetWoApprovalByRound :one
SELECT id, work_order_id, work_order_round_id, reviewer_id, decision, repair_date, new_work_order_id, note, reviewed_at, created_at, updated_at, created_by, updated_by FROM rtu.wo_approvals WHERE work_order_round_id = $1::uuid
`

func (q *Queries) GetWoApprovalByRound(ctx context.Context, workOrderRoundID uuid.UUID) (WoApproval, error) {
	row := q.db.QueryRow(ctx, getWoApprovalByRound, workOrderRoundID)
	var i WoApproval
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.WorkOrderRoundID,
		&i.ReviewerID,
		&i.Decision,
		&i.RepairDate,
		&i.NewWorkOrderID,
		&i.Note,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const listWoApprovalsByWorkOrder = `-- name: ListWoApprovalsByWorkOrder :many
SELECT id, work_order_id, work_order_round_id, reviewer_id, decision, repair_date, new_work_order_id, note, reviewed_at, created_at, updated_at, created_by, updated_by FROM rtu.wo_approvals
WHERE work_order_id = $1::uuid
ORDER BY reviewed_at ASC
`

func (q *Queries) ListWoApprovalsByWorkOrder(ctx context.Context, workOrderID uuid.UUID) ([]WoApproval, error) {
	rows, err := q.db.Query(ctx, listWoApprovalsByWorkOrder, workOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WoApproval{}
	for rows.Next() {
		var i WoApproval
		if err := rows.Scan(
			&i.ID,
			&i.WorkOrderID,
			&i.WorkOrderRoundID,
			&i.ReviewerID,
			&i.Decision,
			&i.RepairDate,
			&i.NewWorkOrderID,
			&i.Note,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
