// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: work_order_rounds.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const checkInWorkOrderRound = `-- name: CheckInWorkOrderRound :one
UPDATE rtu.work_order_rounds SET
    check_in_at  = $1::timestamptz,
    check_in_lat = $2::numeric,
    check_in_lng = $3::numeric,
    updated_by   = $4::uuid
WHERE id = $5::uuid AND check_in_at IS NULL
RETURNING id, work_order_id, round_no, assigned_to, assigned_by, assigned_at, check_in_at, check_in_lat, check_in_lng, check_out_at, check_out_lat, check_out_lng, submitted_at, active, created_at, updated_at, created_by, updated_by
`

type CheckInWorkOrderRoundParams struct {
	CheckInAt  time.Time        `db:"check_in_at" json:"check_in_at"`
	CheckInLat *decimal.Decimal `db:"check_in_lat" json:"check_in_lat"`
	CheckInLng *decimal.Decimal `db:"check_in_lng" json:"check_in_lng"`
	UpdatedBy  *uuid.UUID       `db:"updated_by" json:"updated_by"`
	ID         uuid.UUID        `db:"id" json:"id"`
}

func (q *Queries) CheckInWorkOrderRound(ctx context.Context, arg CheckInWorkOrderRoundParams) (WorkOrderRound, error) {
	row := q.db.QueryRow(ctx, checkInWorkOrderRound,
		arg.CheckInAt,
		arg.CheckInLat,
		arg.CheckInLng,
		arg.UpdatedBy,
		arg.ID,
	)
	var i WorkOrderRound
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.RoundNo,
		&i.AssignedTo,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.CheckInAt,
		&i.CheckInLat,
		&i.CheckInLng,
		&i.CheckOutAt,
		&i.CheckOutLat,
		&i.CheckOutLng,
		&i.SubmittedAt,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const checkOutWorkOrderRound = `-- name: CheckOutWorkOrderRound :one
UPDATE rtu.work_order_rounds SET
    check_out_at  = $1::timestamptz,
    check_out_lat = $2::numeric,
    check_out_lng = $3::numeric,
    updated_by    = $4::uuid
WHERE id = $5::uuid AND check_in_at IS NOT NULL AND check_out_at IS NULL
RETURNING id, work_order_id, round_no, assigned_to, assigned_by, assigned_at, check_in_at, check_in_lat, check_in_lng, check_out_at, check_out_lat, check_out_lng, submitted_at, active, created_at, updated_at, created_by, updated_by
`

type CheckOutWorkOrderRoundParams struct {
	CheckOutAt  time.Time        `db:"check_out_at" json:"check_out_at"`
	CheckOutLat *decimal.Decimal `db:"check_out_lat" json:"check_out_lat"`
	CheckOutLng *decimal.Decimal `db:"check_out_lng" json:"check_out_lng"`
	UpdatedBy   *uuid.UUID       `db:"updated_by" json:"updated_by"`
	ID          uuid.UUID        `db:"id" json:"id"`
}

func (q *Queries) CheckOutWorkOrderRound(ctx context.Context, arg CheckOutWorkOrderRoundParams) (WorkOrderRound, error) {
	row := q.db.QueryRow(ctx, checkOutWorkOrderRound,
		arg.CheckOutAt,
		arg.CheckOutLat,
		arg.CheckOutLng,
		arg.UpdatedBy,
		arg.ID,
	)
	var i WorkOrderRound
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.RoundNo,
		&i.AssignedTo,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.CheckInAt,
		&i.CheckInLat,
		&i.CheckInLng,
		&i.CheckOutAt,
		&i.CheckOutLat,
		&i.CheckOutLng,
		&i.SubmittedAt,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const createWorkOrderRound = `-- name: CreateWorkOrderRound :one
INSERT INTO rtu.work_order_rounds (
    work_order_id, round_no, assigned_to, assigned_by, assigned_at, created_by, updated_by
)
VALUES (
    $1::uuid,
    $2::smallint,
    $3::uuid,
    $4::uuid,
    $5::timestamptz,
    $6::uuid,
    $7::uuid
)
RETURNING id, work_order_id, round_no, assigned_to, assigned_by, assigned_at, check_in_at, check_in_lat, check_in_lng, check_out_at, check_out_lat, check_out_lng, submitted_at, active, created_at, updated_at, created_by, updated_by
`

type CreateWorkOrderRoundParams struct {
	WorkOrderID uuid.UUID  `db:"work_order_id" json:"work_order_id"`
	RoundNo     int16      `db:"round_no" json:"round_no"`
	AssignedTo  uuid.UUID  `db:"assigned_to" json:"assigned_to"`
	AssignedBy  uuid.UUID  `db:"assigned_by" json:"assigned_by"`
	AssignedAt  time.Time  `db:"assigned_at" json:"assigned_at"`
	CreatedBy   *uuid.UUID `db:"created_by" json:"created_by"`
	UpdatedBy   *uuid.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) CreateWorkOrderRound(ctx context.Context, arg CreateWorkOrderRoundParams) (WorkOrderRound, error) {
	row := q.db.QueryRow(ctx, createWorkOrderRound,
		arg.WorkOrderID,
		arg.RoundNo,
		arg.AssignedTo,
		arg.AssignedBy,
		arg.AssignedAt,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i WorkOrderRound
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.RoundNo,
		&i.AssignedTo,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.CheckInAt,
		&i.CheckInLat,
		&i.CheckInLng,
		&i.CheckOutAt,
		&i.CheckOutLat,
		&i.CheckOutLng,
		&i.SubmittedAt,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getWorkOrderRound = `-- name: GetWorkOrderRound :one
SELECT id, work_order_id, round_no, assigned_to, assigned_by, assigned_at, check_in_at, check_in_lat, check_in_lng, check_out_at, check_out_lat, check_out_lng, submitted_at, active, created_at, updated_at, created_by, updated_by FROM rtu.work_order_rounds WHERE id = $1::uuid
`

func (q *Queries) GetWorkOrderRound(ctx context.Context, id uuid.UUID) (WorkOrderRound, error) {
	row := q.db.QueryRow(ctx, getWorkOrderRound, id)
	var i WorkOrderRound
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.RoundNo,
		&i.AssignedTo,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.CheckInAt,
		&i.CheckInLat,
		&i.CheckInLng,
		&i.CheckOutAt,
		&i.CheckOutLat,
		&i.CheckOutLng,
		&i.SubmittedAt,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const listWorkOrderRoundsByWorkOrder = `-- name: ListWorkOrderRoundsByWorkOrder :many
SELECT id, work_order_id, round_no, assigned_to, assigned_by, assigned_at, check_in_at, check_in_lat, check_in_lng, check_out_at, check_out_lat, check_out_lng, submitted_at, active, created_at, updated_at, created_by, updated_by FROM rtu.work_order_rounds
WHERE work_order_id = $1::uuid
ORDER BY round_no ASC
`

func (q *Queries) ListWorkOrderRoundsByWorkOrder(ctx context.Context, workOrderID uuid.UUID) ([]WorkOrderRound, error) {
	rows, err := q.db.Query(ctx, listWorkOrderRoundsByWorkOrder, workOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkOrderRound{}
	for rows.Next() {
		var i WorkOrderRound
		if err := rows.Scan(
			&i.ID,
			&i.WorkOrderID,
			&i.RoundNo,
			&i.AssignedTo,
			&i.AssignedBy,
			&i.AssignedAt,
			&i.CheckInAt,
			&i.CheckInLat,
			&i.CheckInLng,
			&i.CheckOutAt,
			&i.CheckOutLat,
			&i.CheckOutLng,
			&i.SubmittedAt,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextWorkOrderRoundNo = `-- name: NextWorkOrderRoundNo :one
SELECT (COALESCE(max(round_no), 0) + 1)::smallint AS next_round_no
FROM rtu.work_order_rounds
WHERE work_order_id = $1::uuid
`

func (q *Queries) NextWorkOrderRoundNo(ctx context.Context, workOrderID uuid.UUID) (int16, error) {
	row := q.db.QueryRow(ctx, nextWorkOrderRoundNo, workOrderID)
	var next_round_no int16
	err := row.Scan(&next_round_no)
	return next_round_no, err
}

const setWorkOrderRoundSubmitted = `-- name: SetWorkOrderRoundSubmitted :one
UPDATE rtu.work_order_rounds SET
    submitted_at = COALESCE($1::timestamptz, now()),
    updated_by   = $2::uuid
WHERE id = $3::uuid
RETURNING id, work_order_id, round_no, assigned_to, assigned_by, assigned_at, check_in_at, check_in_lat, check_in_lng, check_out_at, check_out_lat, check_out_lng, submitted_at, active, created_at, updated_at, created_by, updated_by
`

type SetWorkOrderRoundSubmittedParams struct {
	SubmittedAt *time.Time `db:"submitted_at" json:"submitted_at"`
	UpdatedBy   *uuid.UUID `db:"updated_by" json:"updated_by"`
	ID          uuid.UUID  `db:"id" json:"id"`
}

func (q *Queries) SetWorkOrderRoundSubmitted(ctx context.Context, arg SetWorkOrderRoundSubmittedParams) (WorkOrderRound, error) {
	row := q.db.QueryRow(ctx, setWorkOrderRoundSubmitted, arg.SubmittedAt, arg.UpdatedBy, arg.ID)
	var i WorkOrderRound
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.RoundNo,
		&i.AssignedTo,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.CheckInAt,
		&i.CheckInLat,
		&i.CheckInLng,
		&i.CheckOutAt,
		&i.CheckOutLat,
		&i.CheckOutLng,
		&i.SubmittedAt,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const updateWorkOrderRoundAssignment = `-- name: UpdateWorkOrderRoundAssignment :one
UPDATE rtu.work_order_rounds SET
    assigned_to = $1::uuid,
    assigned_by = $2::uuid,
    assigned_at = $3::timestamptz,
    updated_by  = $4::uuid
WHERE id = $5::uuid AND check_in_at IS NULL
RETURNING id, work_order_id, round_no, assigned_to, assigned_by, assigned_at, check_in_at, check_in_lat, check_in_lng, check_out_at, check_out_lat, check_out_lng, submitted_at, active, created_at, updated_at, created_by, updated_by
`

type UpdateWorkOrderRoundAssignmentParams struct {
	AssignedTo uuid.UUID  `db:"assigned_to" json:"assigned_to"`
	AssignedBy uuid.UUID  `db:"assigned_by" json:"assigned_by"`
	AssignedAt time.Time  `db:"assigned_at" json:"assigned_at"`
	UpdatedBy  *uuid.UUID `db:"updated_by" json:"updated_by"`
	ID         uuid.UUID  `db:"id" json:"id"`
}

// Reassigns the current round in place. Only valid before check-in — once a
// round has started, a rejection must open a new round instead (see
// CreateWorkOrderRound + NextWorkOrderRoundNo).
func (q *Queries) UpdateWorkOrderRoundAssignment(ctx context.Context, arg UpdateWorkOrderRoundAssignmentParams) (WorkOrderRound, error) {
	row := q.db.QueryRow(ctx, updateWorkOrderRoundAssignment,
		arg.AssignedTo,
		arg.AssignedBy,
		arg.AssignedAt,
		arg.UpdatedBy,
		arg.ID,
	)
	var i WorkOrderRound
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.RoundNo,
		&i.AssignedTo,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.CheckInAt,
		&i.CheckInLat,
		&i.CheckInLng,
		&i.CheckOutAt,
		&i.CheckOutLat,
		&i.CheckOutLng,
		&i.SubmittedAt,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
