// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: work_order_activity_logs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createWorkOrderActivityLog = `-- name: CreateWorkOrderActivityLog :one
INSERT INTO rtu.work_order_activity_logs (
    work_order_id, work_order_round_id, action, from_status, to_status,
    from_assignee, to_assignee, note, actor_id
)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::varchar,
    $4::varchar,
    $5::varchar,
    $6::uuid,
    $7::uuid,
    $8::text,
    $9::uuid
)
RETURNING id, work_order_id, work_order_round_id, action, from_status, to_status, from_assignee, to_assignee, note, actor_id, created_at
`

type CreateWorkOrderActivityLogParams struct {
	WorkOrderID      uuid.UUID  `db:"work_order_id" json:"work_order_id"`
	WorkOrderRoundID *uuid.UUID `db:"work_order_round_id" json:"work_order_round_id"`
	Action           string     `db:"action" json:"action"`
	FromStatus       *string    `db:"from_status" json:"from_status"`
	ToStatus         *string    `db:"to_status" json:"to_status"`
	FromAssignee     *uuid.UUID `db:"from_assignee" json:"from_assignee"`
	ToAssignee       *uuid.UUID `db:"to_assignee" json:"to_assignee"`
	Note             *string    `db:"note" json:"note"`
	ActorID          uuid.UUID  `db:"actor_id" json:"actor_id"`
}

func (q *Queries) CreateWorkOrderActivityLog(ctx context.Context, arg CreateWorkOrderActivityLogParams) (WorkOrderActivityLog, error) {
	row := q.db.QueryRow(ctx, createWorkOrderActivityLog,
		arg.WorkOrderID,
		arg.WorkOrderRoundID,
		arg.Action,
		arg.FromStatus,
		arg.ToStatus,
		arg.FromAssignee,
		arg.ToAssignee,
		arg.Note,
		arg.ActorID,
	)
	var i WorkOrderActivityLog
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.WorkOrderRoundID,
		&i.Action,
		&i.FromStatus,
		&i.ToStatus,
		&i.FromAssignee,
		&i.ToAssignee,
		&i.Note,
		&i.ActorID,
		&i.CreatedAt,
	)
	return i, err
}

const listWorkOrderActivityLogs = `-- name: ListWorkOrderActivityLogs :many
SELECT id, work_order_id, work_order_round_id, action, from_status, to_status, from_assignee, to_assignee, note, actor_id, created_at FROM rtu.work_order_activity_logs
WHERE work_order_id = $1::uuid
ORDER BY created_at ASC
`

func (q *Queries) ListWorkOrderActivityLogs(ctx context.Context, workOrderID uuid.UUID) ([]WorkOrderActivityLog, error) {
	rows, err := q.db.Query(ctx, listWorkOrderActivityLogs, workOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkOrderActivityLog{}
	for rows.Next() {
		var i WorkOrderActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.WorkOrderID,
			&i.WorkOrderRoundID,
			&i.Action,
			&i.FromStatus,
			&i.ToStatus,
			&i.FromAssignee,
			&i.ToAssignee,
			&i.Note,
			&i.ActorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
