// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: work_orders.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/rtu-api/internal/httpx"
)

const countOpenWorkOrdersForPanel = `-- name: CountOpenWorkOrdersForPanel :one
SELECT id FROM rtu.work_orders
WHERE panel_id = $1::uuid
  AND work_order_type = $2::varchar
  AND status NOT IN ('COMPLETED', 'CANCELLED')
ORDER BY created_at DESC
LIMIT 1
`

type CountOpenWorkOrdersForPanelParams struct {
	PanelID       uuid.UUID `db:"panel_id" json:"panel_id"`
	WorkOrderType string    `db:"work_order_type" json:"work_order_type"`
}

// Business rule: before opening a new CM work order, check whether an open
// (status <> COMPLETED/CANCELLED) one already exists for the panel to reuse.
func (q *Queries) CountOpenWorkOrdersForPanel(ctx context.Context, arg CountOpenWorkOrdersForPanelParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, countOpenWorkOrdersForPanel, arg.PanelID, arg.WorkOrderType)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const countWorkOrdersByPanelAndType = `-- name: CountWorkOrdersByPanelAndType :one
SELECT count(*)::bigint AS total
FROM rtu.work_orders
WHERE panel_id = $1::uuid AND work_order_type = $2::varchar
`

type CountWorkOrdersByPanelAndTypeParams struct {
	PanelID       uuid.UUID `db:"panel_id" json:"panel_id"`
	WorkOrderType string    `db:"work_order_type" json:"work_order_type"`
}

// Next sequence for work_order_no on a panel (TYPE-PANEL_CODE-0001).
func (q *Queries) CountWorkOrdersByPanelAndType(ctx context.Context, arg CountWorkOrdersByPanelAndTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkOrdersByPanelAndType, arg.PanelID, arg.WorkOrderType)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createWorkOrder = `-- name: CreateWorkOrder :one
INSERT INTO rtu.work_orders (
    work_order_no, work_order_type, pm_schedule_type, panel_id, panel_device_id,
    title, description, priority, source, requested_by, related_work_order_id,
    planned_date, due_date, created_by, updated_by
)
VALUES (
    $1::varchar,
    $2::varchar,
    $3::varchar,
    $4::uuid,
    $5::uuid,
    $6::varchar,
    $7::text,
    COALESCE($8::varchar, 'MEDIUM'),
    COALESCE($9::varchar, 'WORKFLOW'),
    $10::uuid,
    $11::uuid,
    $12::date,
    $13::date,
    $14::uuid,
    $15::uuid
)
RETURNING id, work_order_no, work_order_type, pm_schedule_type, panel_id, panel_device_id, title, description, status, priority, source, requested_by, current_round_id, related_work_order_id, planned_date, due_date, closed_at, active, created_at, updated_at, created_by, updated_by
`

type CreateWorkOrderParams struct {
	WorkOrderNo        string      `db:"work_order_no" json:"work_order_no"`
	WorkOrderType      string      `db:"work_order_type" json:"work_order_type"`
	PmScheduleType     *string     `db:"pm_schedule_type" json:"pm_schedule_type"`
	PanelID            uuid.UUID   `db:"panel_id" json:"panel_id"`
	PanelDeviceID      *uuid.UUID  `db:"panel_device_id" json:"panel_device_id"`
	Title              *string     `db:"title" json:"title"`
	Description        *string     `db:"description" json:"description"`
	Priority           *string     `db:"priority" json:"priority"`
	Source             *string     `db:"source" json:"source"`
	RequestedBy        uuid.UUID   `db:"requested_by" json:"requested_by"`
	RelatedWorkOrderID *uuid.UUID  `db:"related_work_order_id" json:"related_work_order_id"`
	PlannedDate        *httpx.Date `db:"planned_date" json:"planned_date"`
	DueDate            *httpx.Date `db:"due_date" json:"due_date"`
	CreatedBy          *uuid.UUID  `db:"created_by" json:"created_by"`
	UpdatedBy          *uuid.UUID  `db:"updated_by" json:"updated_by"`
}

func (q *Queries) CreateWorkOrder(ctx context.Context, arg CreateWorkOrderParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, createWorkOrder,
		arg.WorkOrderNo,
		arg.WorkOrderType,
		arg.PmScheduleType,
		arg.PanelID,
		arg.PanelDeviceID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.Source,
		arg.RequestedBy,
		arg.RelatedWorkOrderID,
		arg.PlannedDate,
		arg.DueDate,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.WorkOrderNo,
		&i.WorkOrderType,
		&i.PmScheduleType,
		&i.PanelID,
		&i.PanelDeviceID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Source,
		&i.RequestedBy,
		&i.CurrentRoundID,
		&i.RelatedWorkOrderID,
		&i.PlannedDate,
		&i.DueDate,
		&i.ClosedAt,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const findReusableCmWorkOrderForPanel = `-- name: FindReusableCmWorkOrderForPanel :one
SELECT wo.id
FROM rtu.work_orders wo
WHERE wo.panel_id = $1::uuid
  AND wo.work_order_type = 'CM'
  AND wo.status = 'PENDING'
  AND wo.current_round_id IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM rtu.cm_reports cr
    WHERE cr.work_order_round_id = wo.current_round_id
  )
ORDER BY wo.created_at DESC
LIMIT 1
`

// Reuse only a PENDING CM whose current round has no report yet — avoids
// hijacking an in-progress CM or overwriting an existing round report.
func (q *Queries) FindReusableCmWorkOrderForPanel(ctx context.Context, panelID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findReusableCmWorkOrderForPanel, panelID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getWorkOrder = `-- name: GetWorkOrder :one
SELECT id, work_order_no, work_order_type, pm_schedule_type, panel_id, panel_device_id, title, description, status, priority, source, requested_by, current_round_id, related_work_order_id, planned_date, due_date, closed_at, active, created_at, updated_at, created_by, updated_by FROM rtu.work_orders WHERE id = $1::uuid
`

func (q *Queries) GetWorkOrder(ctx context.Context, id uuid.UUID) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, getWorkOrder, id)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.WorkOrderNo,
		&i.WorkOrderType,
		&i.PmScheduleType,
		&i.PanelID,
		&i.PanelDeviceID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Source,
		&i.RequestedBy,
		&i.CurrentRoundID,
		&i.RelatedWorkOrderID,
		&i.PlannedDate,
		&i.DueDate,
		&i.ClosedAt,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const setWorkOrderActive = `-- name: SetWorkOrderActive :one
UPDATE rtu.work_orders SET
    active     = $1::boolean,
    status     = CASE WHEN $1::boolean THEN status ELSE 'CANCELLED' END,
    updated_by = $2::uuid
WHERE id = $3::uuid
RETURNING id, work_order_no, work_order_type, pm_schedule_type, panel_id, panel_device_id, title, description, status, priority, source, requested_by, current_round_id, related_work_order_id, planned_date, due_date, closed_at, active, created_at, updated_at, created_by, updated_by
`

type SetWorkOrderActiveParams struct {
	Active    bool       `db:"active" json:"active"`
	UpdatedBy *uuid.UUID `db:"updated_by" json:"updated_by"`
	ID        uuid.UUID  `db:"id" json:"id"`
}

func (q *Queries) SetWorkOrderActive(ctx context.Context, arg SetWorkOrderActiveParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, setWorkOrderActive, arg.Active, arg.UpdatedBy, arg.ID)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.WorkOrderNo,
		&i.WorkOrderType,
		&i.PmScheduleType,
		&i.PanelID,
		&i.PanelDeviceID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Source,
		&i.RequestedBy,
		&i.CurrentRoundID,
		&i.RelatedWorkOrderID,
		&i.PlannedDate,
		&i.DueDate,
		&i.ClosedAt,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const setWorkOrderCurrentRound = `-- name: SetWorkOrderCurrentRound :one
UPDATE rtu.work_orders SET
    current_round_id = $1::uuid,
    updated_by        = $2::uuid
WHERE id = $3::uuid
RETURNING id, work_order_no, work_order_type, pm_schedule_type, panel_id, panel_device_id, title, description, status, priority, source, requested_by, current_round_id, related_work_order_id, planned_date, due_date, closed_at, active, created_at, updated_at, created_by, updated_by
`

type SetWorkOrderCurrentRoundParams struct {
	CurrentRoundID uuid.UUID  `db:"current_round_id" json:"current_round_id"`
	UpdatedBy      *uuid.UUID `db:"updated_by" json:"updated_by"`
	ID             uuid.UUID  `db:"id" json:"id"`
}

func (q *Queries) SetWorkOrderCurrentRound(ctx context.Context, arg SetWorkOrderCurrentRoundParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, setWorkOrderCurrentRound, arg.CurrentRoundID, arg.UpdatedBy, arg.ID)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.WorkOrderNo,
		&i.WorkOrderType,
		&i.PmScheduleType,
		&i.PanelID,
		&i.PanelDeviceID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Source,
		&i.RequestedBy,
		&i.CurrentRoundID,
		&i.RelatedWorkOrderID,
		&i.PlannedDate,
		&i.DueDate,
		&i.ClosedAt,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const updateWorkOrder = `-- name: UpdateWorkOrder :one
UPDATE rtu.work_orders SET
    pm_schedule_type = CASE WHEN $1::boolean THEN $2::varchar ELSE pm_schedule_type END,
    panel_device_id = CASE WHEN $3::boolean THEN $4::uuid ELSE panel_device_id END,
    title           = CASE WHEN $5::boolean THEN $6::varchar ELSE title END,
    description     = CASE WHEN $7::boolean THEN $8::text ELSE description END,
    priority        = CASE WHEN $9::boolean THEN $10::varchar ELSE priority END,
    planned_date    = CASE WHEN $11::boolean THEN $12::date ELSE planned_date END,
    due_date        = CASE WHEN $13::boolean THEN $14::date ELSE due_date END,
    updated_by      = $15::uuid
WHERE id = $16::uuid
RETURNING id, work_order_no, work_order_type, pm_schedule_type, panel_id, panel_device_id, title, description, status, priority, source, requested_by, current_round_id, related_work_order_id, planned_date, due_date, closed_at, active, created_at, updated_at, created_by, updated_by
`

type UpdateWorkOrderParams struct {
	PmScheduleTypeDoUpdate bool        `db:"pm_schedule_type_do_update" json:"pm_schedule_type_do_update"`
	PmScheduleType         *string     `db:"pm_schedule_type" json:"pm_schedule_type"`
	PanelDeviceIDDoUpdate  bool        `db:"panel_device_id_do_update" json:"panel_device_id_do_update"`
	PanelDeviceID          *uuid.UUID  `db:"panel_device_id" json:"panel_device_id"`
	TitleDoUpdate          bool        `db:"title_do_update" json:"title_do_update"`
	Title                  *string     `db:"title" json:"title"`
	DescriptionDoUpdate    bool        `db:"description_do_update" json:"description_do_update"`
	Description            *string     `db:"description" json:"description"`
	PriorityDoUpdate       bool        `db:"priority_do_update" json:"priority_do_update"`
	Priority               string      `db:"priority" json:"priority"`
	PlannedDateDoUpdate    bool        `db:"planned_date_do_update" json:"planned_date_do_update"`
	PlannedDate            *httpx.Date `db:"planned_date" json:"planned_date"`
	DueDateDoUpdate        bool        `db:"due_date_do_update" json:"due_date_do_update"`
	DueDate                *httpx.Date `db:"due_date" json:"due_date"`
	UpdatedBy              *uuid.UUID  `db:"updated_by" json:"updated_by"`
	ID                     uuid.UUID   `db:"id" json:"id"`
}

func (q *Queries) UpdateWorkOrder(ctx context.Context, arg UpdateWorkOrderParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, updateWorkOrder,
		arg.PmScheduleTypeDoUpdate,
		arg.PmScheduleType,
		arg.PanelDeviceIDDoUpdate,
		arg.PanelDeviceID,
		arg.TitleDoUpdate,
		arg.Title,
		arg.DescriptionDoUpdate,
		arg.Description,
		arg.PriorityDoUpdate,
		arg.Priority,
		arg.PlannedDateDoUpdate,
		arg.PlannedDate,
		arg.DueDateDoUpdate,
		arg.DueDate,
		arg.UpdatedBy,
		arg.ID,
	)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.WorkOrderNo,
		&i.WorkOrderType,
		&i.PmScheduleType,
		&i.PanelID,
		&i.PanelDeviceID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Source,
		&i.RequestedBy,
		&i.CurrentRoundID,
		&i.RelatedWorkOrderID,
		&i.PlannedDate,
		&i.DueDate,
		&i.ClosedAt,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const updateWorkOrderStatus = `-- name: UpdateWorkOrderStatus :one
UPDATE rtu.work_orders SET
    status     = $1::varchar,
    closed_at  = CASE WHEN $2::boolean THEN $3::timestamptz ELSE closed_at END,
    updated_by = $4::uuid
WHERE id = $5::uuid
RETURNING id, work_order_no, work_order_type, pm_schedule_type, panel_id, panel_device_id, title, description, status, priority, source, requested_by, current_round_id, related_work_order_id, planned_date, due_date, closed_at, active, created_at, updated_at, created_by, updated_by
`

type UpdateWorkOrderStatusParams struct {
	Status           string     `db:"status" json:"status"`
	ClosedAtDoUpdate bool       `db:"closed_at_do_update" json:"closed_at_do_update"`
	ClosedAt         *time.Time `db:"closed_at" json:"closed_at"`
	UpdatedBy        *uuid.UUID `db:"updated_by" json:"updated_by"`
	ID               uuid.UUID  `db:"id" json:"id"`
}

func (q *Queries) UpdateWorkOrderStatus(ctx context.Context, arg UpdateWorkOrderStatusParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, updateWorkOrderStatus,
		arg.Status,
		arg.ClosedAtDoUpdate,
		arg.ClosedAt,
		arg.UpdatedBy,
		arg.ID,
	)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.WorkOrderNo,
		&i.WorkOrderType,
		&i.PmScheduleType,
		&i.PanelID,
		&i.PanelDeviceID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Source,
		&i.RequestedBy,
		&i.CurrentRoundID,
		&i.RelatedWorkOrderID,
		&i.PlannedDate,
		&i.DueDate,
		&i.ClosedAt,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const workOrderExists = `-- name: WorkOrderExists :one
SELECT EXISTS (SELECT 1 FROM rtu.work_orders WHERE id = $1::uuid) AS found
`

func (q *Queries) WorkOrderExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, workOrderExists, id)
	var found bool
	err := row.Scan(&found)
	return found, err
}
