// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: work_order_problem_topics.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const deleteWorkOrderProblemTopic = `-- name: DeleteWorkOrderProblemTopic :exec
DELETE FROM rtu.work_order_problem_topics
WHERE work_order_id = $1::uuid
  AND problem_topic_id = $2::uuid
`

type DeleteWorkOrderProblemTopicParams struct {
	WorkOrderID    uuid.UUID `db:"work_order_id" json:"work_order_id"`
	ProblemTopicID uuid.UUID `db:"problem_topic_id" json:"problem_topic_id"`
}

func (q *Queries) DeleteWorkOrderProblemTopic(ctx context.Context, arg DeleteWorkOrderProblemTopicParams) error {
	_, err := q.db.Exec(ctx, deleteWorkOrderProblemTopic, arg.WorkOrderID, arg.ProblemTopicID)
	return err
}

const deleteWorkOrderProblemTopicsByWorkOrder = `-- name: DeleteWorkOrderProblemTopicsByWorkOrder :exec
DELETE FROM rtu.work_order_problem_topics
WHERE work_order_id = $1::uuid
`

func (q *Queries) DeleteWorkOrderProblemTopicsByWorkOrder(ctx context.Context, workOrderID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkOrderProblemTopicsByWorkOrder, workOrderID)
	return err
}

const insertWorkOrderProblemTopic = `-- name: InsertWorkOrderProblemTopic :exec
INSERT INTO rtu.work_order_problem_topics (work_order_id, problem_topic_id, sort_order)
VALUES ($1::uuid, $2::uuid, $3::smallint)
`

type InsertWorkOrderProblemTopicParams struct {
	WorkOrderID    uuid.UUID `db:"work_order_id" json:"work_order_id"`
	ProblemTopicID uuid.UUID `db:"problem_topic_id" json:"problem_topic_id"`
	SortOrder      int16     `db:"sort_order" json:"sort_order"`
}

func (q *Queries) InsertWorkOrderProblemTopic(ctx context.Context, arg InsertWorkOrderProblemTopicParams) error {
	_, err := q.db.Exec(ctx, insertWorkOrderProblemTopic, arg.WorkOrderID, arg.ProblemTopicID, arg.SortOrder)
	return err
}

const listProblemTopicsByWorkOrder = `-- name: ListProblemTopicsByWorkOrder :many
SELECT pt.id, pt.code, pt.name, wopt.sort_order
FROM rtu.work_order_problem_topics wopt
JOIN rtu.problem_topics pt ON pt.id = wopt.problem_topic_id
WHERE wopt.work_order_id = $1::uuid
ORDER BY wopt.sort_order, pt.sort_order, pt.code
`

type ListProblemTopicsByWorkOrderRow struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Code      string    `db:"code" json:"code"`
	Name      string    `db:"name" json:"name"`
	SortOrder int16     `db:"sort_order" json:"sort_order"`
}

func (q *Queries) ListProblemTopicsByWorkOrder(ctx context.Context, workOrderID uuid.UUID) ([]ListProblemTopicsByWorkOrderRow, error) {
	rows, err := q.db.Query(ctx, listProblemTopicsByWorkOrder, workOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProblemTopicsByWorkOrderRow{}
	for rows.Next() {
		var i ListProblemTopicsByWorkOrderRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProblemTopicsByWorkOrders = `-- name: ListProblemTopicsByWorkOrders :many
SELECT
    wopt.work_order_id,
    pt.id,
    pt.code,
    pt.name,
    wopt.sort_order
FROM rtu.work_order_problem_topics wopt
JOIN rtu.problem_topics pt ON pt.id = wopt.problem_topic_id
WHERE wopt.work_order_id = ANY($1::uuid[])
ORDER BY wopt.work_order_id, wopt.sort_order, pt.sort_order, pt.code
`

type ListProblemTopicsByWorkOrdersRow struct {
	WorkOrderID uuid.UUID `db:"work_order_id" json:"work_order_id"`
	ID          uuid.UUID `db:"id" json:"id"`
	Code        string    `db:"code" json:"code"`
	Name        string    `db:"name" json:"name"`
	SortOrder   int16     `db:"sort_order" json:"sort_order"`
}

func (q *Queries) ListProblemTopicsByWorkOrders(ctx context.Context, workOrderIds []uuid.UUID) ([]ListProblemTopicsByWorkOrdersRow, error) {
	rows, err := q.db.Query(ctx, listProblemTopicsByWorkOrders, workOrderIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProblemTopicsByWorkOrdersRow{}
	for rows.Next() {
		var i ListProblemTopicsByWorkOrdersRow
		if err := rows.Scan(
			&i.WorkOrderID,
			&i.ID,
			&i.Code,
			&i.Name,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextWorkOrderProblemTopicSortOrder = `-- name: NextWorkOrderProblemTopicSortOrder :one
SELECT COALESCE(MAX(sort_order), -1)::smallint AS next_sort
FROM rtu.work_order_problem_topics
WHERE work_order_id = $1::uuid
`

func (q *Queries) NextWorkOrderProblemTopicSortOrder(ctx context.Context, workOrderID uuid.UUID) (int16, error) {
	row := q.db.QueryRow(ctx, nextWorkOrderProblemTopicSortOrder, workOrderID)
	var next_sort int16
	err := row.Scan(&next_sort)
	return next_sort, err
}

const workOrderHasProblemTopic = `-- name: WorkOrderHasProblemTopic :one
SELECT EXISTS (
    SELECT 1 FROM rtu.work_order_problem_topics
    WHERE work_order_id = $1::uuid
      AND problem_topic_id = $2::uuid
) AS found
`

type WorkOrderHasProblemTopicParams struct {
	WorkOrderID    uuid.UUID `db:"work_order_id" json:"work_order_id"`
	ProblemTopicID uuid.UUID `db:"problem_topic_id" json:"problem_topic_id"`
}

func (q *Queries) WorkOrderHasProblemTopic(ctx context.Context, arg WorkOrderHasProblemTopicParams) (bool, error) {
	row := q.db.QueryRow(ctx, workOrderHasProblemTopic, arg.WorkOrderID, arg.ProblemTopicID)
	var found bool
	err := row.Scan(&found)
	return found, err
}
